package provider

// Note:  This file is automatically generated.  Manually made changes
// will be overwritten when the provider is generated.

import (
	"context"
	"encoding/json"
	"strings"

	sdwan "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk"
	sdwan_schema "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/schemas"
	sdwan_client "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/services"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// +-----------------------------------------------------------------
// | Schema Map Summary (size=goLangStructMap=1)
// | Computed Resource Name=sites_elements_securityzones
// +-----------------------------------------------------------------
// | ElementSecurityZoneScreen HasID=true
// +-----------------------------------------------------------------

// Data source.
var (
	_ datasource.DataSource              = &elementSecurityZoneDataSource{}
	_ datasource.DataSourceWithConfigure = &elementSecurityZoneDataSource{}
)

// To enable this data source for TF Provider, go to `provider.go` and inject this into the function
// as below:
//
//	func (p *SdwanProvider) DataSources(_ context.Context) []func() datasource.DataSource {
//	  	return []func() datasource.DataSource{
//	     ... <other existing data sources>
//	     NewElementSecurityZoneDataSource,
//	     // -- append next datasource above -- //
//	     }
//	  }
func NewElementSecurityZoneDataSource() datasource.DataSource {
	return &elementSecurityZoneDataSource{}
}

type elementSecurityZoneDataSource struct {
	client *sdwan.Client
}

// Metadata returns the data source type name.
func (d *elementSecurityZoneDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "prismasdwan_element_security_zone"
}

// Schema defines the schema for this data source.
func (d *elementSecurityZoneDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Retrieves a config item.",

		Attributes: map[string]dsschema.Attribute{
			"tfid": dsschema.StringAttribute{
				Computed: true,
			},
			// rest all properties to be read from GET API Schema schema=ElementSecurityZoneScreen
			// generic x_parameters is added to accomodate path parameters
			"x_parameters": dsschema.MapAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				ElementType: types.StringType,
			},
			// property: name=_etag, type=INTEGER macro=rss_schema
			"x_etag": dsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_etag, type=INTEGER macro=rss_schema
			// property: name=_schema, type=INTEGER macro=rss_schema
			"x_schema": dsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_schema, type=INTEGER macro=rss_schema
			// property: name=id, type=STRING macro=rss_schema
			"id": dsschema.StringAttribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=id, type=STRING macro=rss_schema
			// property: name=interface_ids, type=ARRAY_PRIMITIVE macro=rss_schema
			"interface_ids": dsschema.ListAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ElementType: types.StringType,
			},
			// key name holder for attribute: name=interface_ids, type=ARRAY_PRIMITIVE macro=rss_schema
			// property: name=lannetwork_ids, type=ARRAY_PRIMITIVE macro=rss_schema
			"lannetwork_ids": dsschema.ListAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ElementType: types.StringType,
			},
			// key name holder for attribute: name=lannetwork_ids, type=ARRAY_PRIMITIVE macro=rss_schema
			// property: name=waninterface_ids, type=ARRAY_PRIMITIVE macro=rss_schema
			"waninterface_ids": dsschema.ListAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ElementType: types.StringType,
			},
			// key name holder for attribute: name=waninterface_ids, type=ARRAY_PRIMITIVE macro=rss_schema
			// property: name=wanoverlay_ids, type=ARRAY_PRIMITIVE macro=rss_schema
			"wanoverlay_ids": dsschema.ListAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ElementType: types.StringType,
			},
			// key name holder for attribute: name=wanoverlay_ids, type=ARRAY_PRIMITIVE macro=rss_schema
			// property: name=zone_id, type=STRING macro=rss_schema
			"zone_id": dsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=zone_id, type=STRING macro=rss_schema
		},
	}
}

// Configure prepares the struct.
func (d *elementSecurityZoneDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*sdwan.Client)
}

// Read performs Read for the struct.
func (d *elementSecurityZoneDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state dsModelElementSecurityZoneScreen
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// pointers
	diagnostics := &resp.Diagnostics

	// Basic logging.
	tflog.Info(ctx, "performing datasource read", map[string]any{
		"terraform_provider_function": "Read",
		"resource_name":               "prismasdwan_element_security_zone",
	})

	tfid := state.Tfid.ValueString()
	tokens := strings.Split(tfid, IdSeparator)
	if len(tokens) != 3 {
		resp.Diagnostics.AddError("error in prismasdwan_element_security_zone ID format", "Expected 3 tokens")
		return
	}

	// Prepare to read the config.
	svc := sdwan_client.NewClient(d.client)

	// Prepare input for the API endpoint.
	read_request := &sdwan_client.SdwanClientRequestResponse{}
	read_request.Method = "GET"
	read_request.Path = "/sdwan/v2.0/api/sites/{site_id}/elements/{element_id}/securityzones/{security_zone_id}"

	// handle parameters
	params := make(map[string]*string)
	read_request.PathParameters = &params
	params["site_id"] = &tokens[0]
	params["element_id"] = &tokens[1]
	params["security_zone_id"] = &tokens[2]

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, read_request)
	if read_request.ResponseErr != nil {
		if IsObjectNotFound(*read_request.ResponseErr) {
			resp.State.RemoveResource(ctx)
		} else {
			resp.Diagnostics.AddError("error reading prismasdwan_element_security_zone", (*read_request.ResponseErr).Error())
		}
		return
	}

	// Create the Terraform ID.
	var idBuilder strings.Builder
	idBuilder.WriteString("x")

	// Store the answer to state.
	state.Tfid = types.StringValue(idBuilder.String())
	// start copying attributes
	var ans sdwan_schema.ElementSecurityZoneScreen
	// copy from json response
	json_err := json.Unmarshal(*read_request.ResponseBytes, &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to ElementSecurityZoneScreen", json_err.Error())
		return
	}

	// lets copy all items into state schema=ElementSecurityZoneScreen
	// copy_to_state: state=state prefix=dsModel ans=ans properties=8
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=interface_ids, type=ARRAY_PRIMITIVE macro=copy_to_state
	varInterfaceIds, errInterfaceIds := types.ListValueFrom(ctx, types.StringType, ans.InterfaceIds)
	state.InterfaceIds = varInterfaceIds
	resp.Diagnostics.Append(errInterfaceIds.Errors()...)
	// property: name=lannetwork_ids, type=ARRAY_PRIMITIVE macro=copy_to_state
	varLannetworkIds, errLannetworkIds := types.ListValueFrom(ctx, types.StringType, ans.LannetworkIds)
	state.LannetworkIds = varLannetworkIds
	resp.Diagnostics.Append(errLannetworkIds.Errors()...)
	// property: name=waninterface_ids, type=ARRAY_PRIMITIVE macro=copy_to_state
	varWaninterfaceIds, errWaninterfaceIds := types.ListValueFrom(ctx, types.StringType, ans.WaninterfaceIds)
	state.WaninterfaceIds = varWaninterfaceIds
	resp.Diagnostics.Append(errWaninterfaceIds.Errors()...)
	// property: name=wanoverlay_ids, type=ARRAY_PRIMITIVE macro=copy_to_state
	varWanoverlayIds, errWanoverlayIds := types.ListValueFrom(ctx, types.StringType, ans.WanoverlayIds)
	state.WanoverlayIds = varWanoverlayIds
	resp.Diagnostics.Append(errWanoverlayIds.Errors()...)
	// property: name=zone_id, type=STRING macro=copy_to_state
	state.ZoneId = types.StringPointerValue(ans.ZoneId)

	// Done.
	diagnostics.Append(resp.State.Set(ctx, &state)...)
}
