package provider

// Note:  This file is automatically generated.  Manually made changes
// will be overwritten when the provider is generated.

import (
	"context"
	"encoding/json"
	"strings"

	sdwan "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk"
	sdwan_schema "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/schemas"
	sdwan_client "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/services"
	"github.com/tidwall/gjson"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// +-----------------------------------------------------------------
// | Schema Map Summary (size=goLangStructMap=2)
// | Computed Resource Name=elements_radii
// +-----------------------------------------------------------------
// | RadiusConfiguration HasID=false
// | ElementRadiusScreen HasID=true
// +-----------------------------------------------------------------

// Data source.
var (
	_ datasource.DataSource              = &elementRadiusDataSource{}
	_ datasource.DataSourceWithConfigure = &elementRadiusDataSource{}
)

// To enable this data source for TF Provider, go to `provider.go` and inject this into the function
// as below:
//
//	func (p *SdwanProvider) DataSources(_ context.Context) []func() datasource.DataSource {
//	  	return []func() datasource.DataSource{
//	     ... <other existing data sources>
//	     NewElementRadiusDataSource,
//	     // -- append next datasource above -- //
//	     }
//	  }
func NewElementRadiusDataSource() datasource.DataSource {
	return &elementRadiusDataSource{}
}

type elementRadiusDataSource struct {
	client *sdwan.Client
}

type dsModelWithFilterElementRadius struct {
	Filters      types.Map                     `tfsdk:"filters"`
	TfParameters types.Map                     `tfsdk:"x_parameters"` // Generic Map for Path Ids
	Etag         types.Int64                   `tfsdk:"x_etag"`       // propertyName=_etag type=INTEGER
	Schema       types.Int64                   `tfsdk:"x_schema"`     // propertyName=_schema type=INTEGER
	Items        []*dsModelElementRadiusScreen `tfsdk:"items"`
}

// Metadata returns the data source type name.
func (d *elementRadiusDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "prismasdwan_element_radius"
}

// Schema defines the schema for this data source.
func (d *elementRadiusDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dsschema.Schema{
		Description: "Retrieves a config item.",
		Attributes: map[string]dsschema.Attribute{
			"filters": dsschema.MapAttribute{
				Required:    true,
				Computed:    false,
				Optional:    false,
				ElementType: types.StringType,
			},
			// generic x_parameters is added to accomodate path parameters
			"x_parameters": dsschema.MapAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				ElementType: types.StringType,
			},
			// property: name=_etag, type=INTEGER macro=rss_schema
			"x_etag": dsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_etag, type=INTEGER macro=rss_schema
			// property: name=_schema, type=INTEGER macro=rss_schema
			"x_schema": dsschema.Int64Attribute{
				Required: false,
				Computed: true,
				Optional: true,
			},
			"items": dsschema.ListNestedAttribute{
				Computed: true,
				NestedObject: dsschema.NestedAttributeObject{
					Attributes: map[string]dsschema.Attribute{
						// rest all properties to be read from GET API Schema schema=ElementRadiusScreen
						// property: name=_etag, type=INTEGER macro=rss_schema
						"x_etag": dsschema.Int64Attribute{
							Required:  false,
							Computed:  true,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=_etag, type=INTEGER macro=rss_schema
						// property: name=_schema, type=INTEGER macro=rss_schema
						"x_schema": dsschema.Int64Attribute{
							Required:  false,
							Computed:  true,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=_schema, type=INTEGER macro=rss_schema
						// property: name=description, type=STRING macro=rss_schema
						"description": dsschema.StringAttribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=description, type=STRING macro=rss_schema
						// property: name=id, type=STRING macro=rss_schema
						"id": dsschema.StringAttribute{
							Required:  false,
							Computed:  true,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=id, type=STRING macro=rss_schema
						// property: name=name, type=STRING macro=rss_schema
						"name": dsschema.StringAttribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=name, type=STRING macro=rss_schema
						// property: name=override_indicator, type=ARRAY_PRIMITIVE macro=rss_schema
						"override_indicator": dsschema.ListAttribute{
							Required:    false,
							Computed:    false,
							Optional:    true,
							Sensitive:   false,
							ElementType: types.StringType,
						},
						// key name holder for attribute: name=override_indicator, type=ARRAY_PRIMITIVE macro=rss_schema
						// property: name=radius_configuration, type=ARRAY_REFERENCE macro=rss_schema
						"radius_configuration": dsschema.ListNestedAttribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
							NestedObject: dsschema.NestedAttributeObject{
								Attributes: map[string]dsschema.Attribute{
									// property: name=accounting_port, type=INTEGER macro=rss_schema
									"accounting_port": dsschema.Int64Attribute{
										Required:  false,
										Computed:  false,
										Optional:  true,
										Sensitive: false,
									},
									// key name holder for attribute: name=accounting_port, type=INTEGER macro=rss_schema
									// property: name=authentication_port, type=INTEGER macro=rss_schema
									"authentication_port": dsschema.Int64Attribute{
										Required:  false,
										Computed:  false,
										Optional:  true,
										Sensitive: false,
									},
									// key name holder for attribute: name=authentication_port, type=INTEGER macro=rss_schema
									// property: name=ip_version, type=INTEGER macro=rss_schema
									"ip_version": dsschema.Int64Attribute{
										Required:  false,
										Computed:  false,
										Optional:  true,
										Sensitive: false,
									},
									// key name holder for attribute: name=ip_version, type=INTEGER macro=rss_schema
									// property: name=priority, type=INTEGER macro=rss_schema
									"priority": dsschema.Int64Attribute{
										Required:  false,
										Computed:  false,
										Optional:  true,
										Sensitive: false,
									},
									// key name holder for attribute: name=priority, type=INTEGER macro=rss_schema
									// property: name=retain_shared_secret, type=BOOLEAN macro=rss_schema
									"retain_shared_secret": dsschema.BoolAttribute{
										Required:  false,
										Computed:  false,
										Optional:  true,
										Sensitive: true,
									},
									// key name holder for attribute: name=retain_shared_secret, type=BOOLEAN macro=rss_schema
									// property: name=server_ip_address, type=STRING macro=rss_schema
									"server_ip_address": dsschema.StringAttribute{
										Required:  false,
										Computed:  false,
										Optional:  true,
										Sensitive: false,
									},
									// key name holder for attribute: name=server_ip_address, type=STRING macro=rss_schema
									// property: name=shared_secret, type=STRING macro=rss_schema
									"shared_secret": dsschema.StringAttribute{
										Required:  false,
										Computed:  false,
										Optional:  true,
										Sensitive: true,
									},
									// key name holder for attribute: name=shared_secret, type=STRING macro=rss_schema
									// property: name=shared_secret_encrypted, type=STRING macro=rss_schema
									"shared_secret_encrypted": dsschema.StringAttribute{
										Required:  false,
										Computed:  false,
										Optional:  true,
										Sensitive: true,
									},
									// key name holder for attribute: name=shared_secret_encrypted, type=STRING macro=rss_schema
								},
							},
						},
						// key name holder for attribute: name=shared_secret_encrypted, type=STRING macro=rss_schema
						// property: name=radius_profile_id, type=STRING macro=rss_schema
						"radius_profile_id": dsschema.StringAttribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=radius_profile_id, type=STRING macro=rss_schema
						// property: name=source_interface_id, type=STRING macro=rss_schema
						"source_interface_id": dsschema.StringAttribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=source_interface_id, type=STRING macro=rss_schema
						// property: name=tags, type=SET_PRIMITIVE macro=rss_schema
						"tags": dsschema.SetAttribute{
							Required:    false,
							Computed:    false,
							Optional:    true,
							Sensitive:   false,
							ElementType: types.StringType,
						},
						// key name holder for attribute: name=tags, type=SET_PRIMITIVE macro=rss_schema
					},
				},
			},
		},
	}
}

// Configure prepares the struct.
func (d *elementRadiusDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	d.client = req.ProviderData.(*sdwan.Client)
}

// Read performs Read for the struct.
func (d *elementRadiusDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {

	var state_with_filter dsModelWithFilterElementRadius
	resp.Diagnostics.Append(req.Config.Get(ctx, &state_with_filter)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// pointers
	diagnostics := &resp.Diagnostics

	// Basic logging.
	tflog.Info(ctx, "performing datasource read", map[string]any{
		"terraform_provider_function": "Read",
		"resource_name":               "prismasdwan_element_radius",
	})

	// Prepare to read the config.
	svc := sdwan_client.NewClient(d.client)

	// Prepare input for the API endpoint.
	get_path := "/sdwan/v2.0/api/elements/{element_id}/radii/{radius_id}"
	list_request := &sdwan_client.SdwanClientRequestResponse{}
	list_request.Method = "GET"
	list_request.Path = get_path[:strings.LastIndex(get_path, "/")]

	// handle parameters
	params := MapStringValueOrNil(ctx, state_with_filter.TfParameters)
	list_request.PathParameters = &params

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, list_request)
	if list_request.ResponseErr != nil {
		if IsObjectNotFound(*list_request.ResponseErr) {
			resp.State.RemoveResource(ctx)
		} else {
			resp.Diagnostics.AddError("error reading prismasdwan_element_radius", (*list_request.ResponseErr).Error())
		}
		return
	}

	// read json string from http response
	response_body_string := string(*list_request.ResponseBytes)
	tflog.Info(ctx, "lookup response from server", map[string]any{
		"path": response_body_string,
	})

	// iterate through items and find the first matching item
	var response listResponse
	json_err := json.Unmarshal([]byte(response_body_string), &response)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to generic map in lookup", json_err.Error())
		return
	}
	// ensure its as array
	for _, item := range response.Items {
		// create json from item
		item_json, item_err := json.Marshal(item)
		tflog.Debug(ctx, "converting json to site", map[string]any{
			"item_json": string(item_json),
		})
		if item_err != nil {
			resp.Diagnostics.AddError("error in json unmarshal to generic map in lookup", item_err.Error())
			return
		}

		value_mismatched := false
		for filter_key, filter_value := range state_with_filter.Filters.Elements() {
			// do a path look up
			path_value := gjson.Get(string(item_json), filter_key).String()
			path_value = strings.Replace(path_value, "\"", "", 2)
			// compare
			if strings.Replace(filter_value.String(), "\"", "", 2) != strings.Replace(path_value, "\"", "", 2) {
				tflog.Debug(ctx, "filter value mis-matched with item, skipping it", map[string]any{
					"filter_key":   filter_key,
					"filter_value": filter_value.String(),
					"path_value":   path_value,
				})
				value_mismatched = true
				break
			}
			tflog.Debug(ctx, "filter value matched with item", map[string]any{
				"filter_key": filter_key,
			})
		}
		if value_mismatched {
			tflog.Debug(ctx, "filter value mis-matched with item, skipping it")
			continue
		}

		// Store the answer to state.
		var state dsModelElementRadiusScreen

		// start copying attributes
		var ans sdwan_schema.ElementRadiusScreen
		// copy from json response
		json_err := json.Unmarshal(item_json, &ans)
		// if found, exit
		if json_err != nil {
			resp.Diagnostics.AddError("error in json unmarshal to ElementRadiusScreen", json_err.Error())
			return
		}

		// lets copy all items into state schema=ElementRadiusScreen
		// copy_to_state: state=state prefix=dsModel ans=ans properties=10
		tflog.Debug(ctx, "copy_to_state state=state prefix=dsModel ans=ans")
		// property: name=_etag, type=INTEGER macro=copy_to_state
		state.Etag = types.Int64PointerValue(ans.Etag)
		// property: name=_schema, type=INTEGER macro=copy_to_state
		state.Schema = types.Int64PointerValue(ans.Schema)
		// property: name=description, type=STRING macro=copy_to_state
		state.Description = types.StringPointerValue(ans.Description)
		// property: name=id, type=STRING macro=copy_to_state
		state.Id = types.StringPointerValue(ans.Id)
		// property: name=name, type=STRING macro=copy_to_state
		state.Name = types.StringPointerValue(ans.Name)
		// property: name=override_indicator, type=ARRAY_PRIMITIVE macro=copy_to_state
		varOverrideIndicator, errOverrideIndicator := types.ListValueFrom(ctx, types.StringType, ans.OverrideIndicator)
		state.OverrideIndicator = varOverrideIndicator
		resp.Diagnostics.Append(errOverrideIndicator.Errors()...)
		// property: name=radius_configuration, type=ARRAY_REFERENCE macro=copy_to_state
		if ans.RadiusConfiguration == nil {
			state.RadiusConfiguration = nil
		} else if len(ans.RadiusConfiguration) == 0 {
			state.RadiusConfiguration = []dsModelRadiusConfiguration{}
		} else {
			state.RadiusConfiguration = make([]dsModelRadiusConfiguration, 0, len(ans.RadiusConfiguration))
			for varLoopRadiusConfigurationIndex, varLoopRadiusConfiguration := range ans.RadiusConfiguration {
				// add a new item
				state.RadiusConfiguration = append(state.RadiusConfiguration, dsModelRadiusConfiguration{})
				// copy_to_state: state=state.RadiusConfiguration[varLoopRadiusConfigurationIndex] prefix=dsModel ans=varLoopRadiusConfiguration properties=8
				tflog.Debug(ctx, "copy_to_state state=state.RadiusConfiguration[varLoopRadiusConfigurationIndex] prefix=dsModel ans=varLoopRadiusConfiguration")
				// property: name=accounting_port, type=INTEGER macro=copy_to_state
				state.RadiusConfiguration[varLoopRadiusConfigurationIndex].AccountingPort = types.Int64PointerValue(varLoopRadiusConfiguration.AccountingPort)
				// property: name=authentication_port, type=INTEGER macro=copy_to_state
				state.RadiusConfiguration[varLoopRadiusConfigurationIndex].AuthenticationPort = types.Int64PointerValue(varLoopRadiusConfiguration.AuthenticationPort)
				// property: name=ip_version, type=INTEGER macro=copy_to_state
				state.RadiusConfiguration[varLoopRadiusConfigurationIndex].IpVersion = types.Int64PointerValue(varLoopRadiusConfiguration.IpVersion)
				// property: name=priority, type=INTEGER macro=copy_to_state
				state.RadiusConfiguration[varLoopRadiusConfigurationIndex].Priority = types.Int64PointerValue(varLoopRadiusConfiguration.Priority)
				// property: name=retain_shared_secret, type=BOOLEAN macro=copy_to_state
				state.RadiusConfiguration[varLoopRadiusConfigurationIndex].RetainSharedSecret = types.BoolPointerValue(varLoopRadiusConfiguration.RetainSharedSecret)
				// property: name=server_ip_address, type=STRING macro=copy_to_state
				state.RadiusConfiguration[varLoopRadiusConfigurationIndex].ServerIpAddress = types.StringPointerValue(varLoopRadiusConfiguration.ServerIpAddress)
				// property: name=shared_secret, type=STRING macro=copy_to_state
				state.RadiusConfiguration[varLoopRadiusConfigurationIndex].SharedSecret = types.StringPointerValue(varLoopRadiusConfiguration.SharedSecret)
				// property: name=shared_secret_encrypted, type=STRING macro=copy_to_state
				state.RadiusConfiguration[varLoopRadiusConfigurationIndex].SharedSecretEncrypted = types.StringPointerValue(varLoopRadiusConfiguration.SharedSecretEncrypted)
			}
		}
		// property: name=radius_profile_id, type=STRING macro=copy_to_state
		state.RadiusProfileId = types.StringPointerValue(ans.RadiusProfileId)
		// property: name=source_interface_id, type=STRING macro=copy_to_state
		state.SourceInterfaceId = types.StringPointerValue(ans.SourceInterfaceId)
		// property: name=tags, type=SET_PRIMITIVE macro=copy_to_state
		varTags, errTags := types.SetValueFrom(ctx, types.StringType, ans.Tags)
		state.Tags = varTags
		resp.Diagnostics.Append(errTags.Errors()...)

		// append the item scanned
		state_with_filter.Items = append(state_with_filter.Items, &state)
	}
	// Done.
	diagnostics.Append(resp.State.Set(ctx, &state_with_filter)...)
}
