package provider

// Note:  This file is automatically generated.  Manually made changes
// will be overwritten when the provider is generated.

import (
	"context"
	"encoding/json"
	"strings"

	sdwan "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk"
	sdwan_schema "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/schemas"
	sdwan_client "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/services"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	rsschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/tidwall/sjson"
)

// +-----------------------------------------------------------------
// | Schema Map Summary (size=goLangStructMap=4)
// | Computed Resource Name=sites_elements_bgppeers
// +-----------------------------------------------------------------
// | AggregatePrefixes HasID=false
// | RouteAggregation HasID=false
// | BGPConfig HasID=false
// | BGPPeerConfigScreenV2N6 HasID=true
// +-----------------------------------------------------------------

// Resource.
var (
	_ resource.Resource                = &elementBgpPeerResource{}
	_ resource.ResourceWithConfigure   = &elementBgpPeerResource{}
	_ resource.ResourceWithImportState = &elementBgpPeerResource{}
)

// To enable this data source for TF Provider, go to `provider.go` and inject this into the function
// as below:
//
//	func (p *SdwanProvider) Resources(_ context.Context) []func() resource.Resource {
//	  	return []func() resource.Resource{
//	     ... <other existing resources>
//	     NewElementBgpPeerResource,
//	     // -- append next resource above -- //
//	     }
//	  }
func NewElementBgpPeerResource() resource.Resource {
	return &elementBgpPeerResource{}
}

type elementBgpPeerResource struct {
	client *sdwan.Client
}

// Metadata returns the data source type name.
func (r *elementBgpPeerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "prismasdwan_element_bgp_peer"
}

// Schema defines the schema for this data source.
func (r *elementBgpPeerResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = rsschema.Schema{
		Description: "Retrieves a config item.",
		Attributes: map[string]rsschema.Attribute{
			"tfid": rsschema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			// rest all properties to be read from GET API Schema schema=BGPPeerConfigScreenV2N6
			// generic x_parameters is added to accomodate path parameters
			"x_parameters": rsschema.MapAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				ElementType: types.StringType,
			},
			// property: name=_etag, type=INTEGER macro=rss_schema
			"x_etag": rsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_etag, type=INTEGER macro=rss_schema
			// property: name=_schema, type=INTEGER macro=rss_schema
			"x_schema": rsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_schema, type=INTEGER macro=rss_schema
			// property: name=advertise_default_route, type=BOOLEAN macro=rss_schema
			"advertise_default_route": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=advertise_default_route, type=BOOLEAN macro=rss_schema
			// property: name=allow_v4_prefixes, type=BOOLEAN macro=rss_schema
			"allow_v4_prefixes": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=allow_v4_prefixes, type=BOOLEAN macro=rss_schema
			// property: name=allow_v6_prefixes, type=BOOLEAN macro=rss_schema
			"allow_v6_prefixes": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=allow_v6_prefixes, type=BOOLEAN macro=rss_schema
			// property: name=bgp_config, type=REFERENCE macro=rss_schema
			"bgp_config": rsschema.SingleNestedAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
				Attributes: map[string]rsschema.Attribute{
					// property: name=adv_interval, type=INTEGER macro=rss_schema
					"adv_interval": rsschema.Int64Attribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=adv_interval, type=INTEGER macro=rss_schema
					// property: name=hold_time, type=INTEGER macro=rss_schema
					"hold_time": rsschema.Int64Attribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=hold_time, type=INTEGER macro=rss_schema
					// property: name=keepalive_time, type=INTEGER macro=rss_schema
					"keepalive_time": rsschema.Int64Attribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=keepalive_time, type=INTEGER macro=rss_schema
					// property: name=local_as_num, type=STRING macro=rss_schema
					"local_as_num": rsschema.StringAttribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=local_as_num, type=STRING macro=rss_schema
					// property: name=md5_secret, type=STRING macro=rss_schema
					"md5_secret": rsschema.StringAttribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: true,
					},
					// key name holder for attribute: name=md5_secret, type=STRING macro=rss_schema
					"md5_secret_internal_key_name": rsschema.StringAttribute{
						Required:  false,
						Computed:  true,
						Optional:  true,
						Sensitive: false,
					},
					// property: name=multi_hop_limit, type=INTEGER macro=rss_schema
					"multi_hop_limit": rsschema.Int64Attribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=multi_hop_limit, type=INTEGER macro=rss_schema
					// property: name=peer_auth_type, type=STRING macro=rss_schema
					"peer_auth_type": rsschema.StringAttribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=peer_auth_type, type=STRING macro=rss_schema
					// property: name=peer_retry_time, type=INTEGER macro=rss_schema
					"peer_retry_time": rsschema.Int64Attribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=peer_retry_time, type=INTEGER macro=rss_schema
				},
			},
			// key name holder for attribute: name=peer_retry_time, type=INTEGER macro=rss_schema
			// property: name=description, type=STRING macro=rss_schema
			"description": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=description, type=STRING macro=rss_schema
			// property: name=id, type=STRING macro=rss_schema
			"id": rsschema.StringAttribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=id, type=STRING macro=rss_schema
			// property: name=name, type=STRING macro=rss_schema
			"name": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=name, type=STRING macro=rss_schema
			// property: name=peer_ip, type=STRING macro=rss_schema
			"peer_ip": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=peer_ip, type=STRING macro=rss_schema
			// property: name=peer_ip_v6, type=STRING macro=rss_schema
			"peer_ip_v6": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=peer_ip_v6, type=STRING macro=rss_schema
			// property: name=peer_type, type=STRING macro=rss_schema
			"peer_type": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=peer_type, type=STRING macro=rss_schema
			// property: name=remote_as_num, type=STRING macro=rss_schema
			"remote_as_num": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=remote_as_num, type=STRING macro=rss_schema
			// property: name=route_aggregation, type=REFERENCE macro=rss_schema
			"route_aggregation": rsschema.SingleNestedAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
				Attributes: map[string]rsschema.Attribute{
					// property: name=aggregate_prefixes, type=ARRAY_REFERENCE macro=rss_schema
					"aggregate_prefixes": rsschema.ListNestedAttribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
						NestedObject: rsschema.NestedAttributeObject{
							Attributes: map[string]rsschema.Attribute{
								// property: name=ip_prefixes, type=ARRAY_PRIMITIVE macro=rss_schema
								"ip_prefixes": rsschema.ListAttribute{
									Required:    false,
									Computed:    false,
									Optional:    true,
									Sensitive:   false,
									ElementType: types.StringType,
								},
								// key name holder for attribute: name=ip_prefixes, type=ARRAY_PRIMITIVE macro=rss_schema
								// property: name=type, type=STRING macro=rss_schema
								"type": rsschema.StringAttribute{
									Required:  false,
									Computed:  false,
									Optional:  true,
									Sensitive: false,
								},
								// key name holder for attribute: name=type, type=STRING macro=rss_schema
							},
						},
					},
					// key name holder for attribute: name=type, type=STRING macro=rss_schema
					// property: name=aggregate_type, type=STRING macro=rss_schema
					"aggregate_type": rsschema.StringAttribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=aggregate_type, type=STRING macro=rss_schema
					// property: name=ipv4_prefix_list_id, type=STRING macro=rss_schema
					"ipv4_prefix_list_id": rsschema.StringAttribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=ipv4_prefix_list_id, type=STRING macro=rss_schema
					// property: name=ipv6_prefix_list_id, type=STRING macro=rss_schema
					"ipv6_prefix_list_id": rsschema.StringAttribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=ipv6_prefix_list_id, type=STRING macro=rss_schema
				},
			},
			// key name holder for attribute: name=ipv6_prefix_list_id, type=STRING macro=rss_schema
			// property: name=route_map_in_id, type=STRING macro=rss_schema
			"route_map_in_id": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=route_map_in_id, type=STRING macro=rss_schema
			// property: name=route_map_out_id, type=STRING macro=rss_schema
			"route_map_out_id": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=route_map_out_id, type=STRING macro=rss_schema
			// property: name=router_id, type=STRING macro=rss_schema
			"router_id": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=router_id, type=STRING macro=rss_schema
			// property: name=scope, type=STRING macro=rss_schema
			"scope": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=scope, type=STRING macro=rss_schema
			// property: name=shutdown, type=BOOLEAN macro=rss_schema
			"shutdown": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=shutdown, type=BOOLEAN macro=rss_schema
			// property: name=tags, type=SET_PRIMITIVE macro=rss_schema
			"tags": rsschema.SetAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ElementType: types.StringType,
			},
			// key name holder for attribute: name=tags, type=SET_PRIMITIVE macro=rss_schema
			// property: name=update_source, type=STRING macro=rss_schema
			"update_source": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=update_source, type=STRING macro=rss_schema
			// property: name=update_source_v6, type=STRING macro=rss_schema
			"update_source_v6": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=update_source_v6, type=STRING macro=rss_schema
			// property: name=vrf_context_id, type=STRING macro=rss_schema
			"vrf_context_id": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=vrf_context_id, type=STRING macro=rss_schema
		},
	}
}

// Configure prepares the struct.
func (r *elementBgpPeerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*sdwan.Client)
}

// in some apis the status code is not consistent and hence we may have to act upon
// specific error codes instead
func (r *elementBgpPeerResource) GetHttpStatusCode(request *sdwan_client.SdwanClientRequestResponse) int {
	if request.ResponseErrorCode == nil {
		return request.ResponseStatusCode
	}
	switch *request.ResponseErrorCode {
	case "OBJECT_NOT_FOUND":
		return 404
	default:
		return request.ResponseStatusCode
	}
}

func (r *elementBgpPeerResource) doPost(ctx context.Context, plan *rsModelBGPPeerConfigScreenV2N6, state *rsModelBGPPeerConfigScreenV2N6, resp *resource.CreateResponse) bool {
	tflog.Info(ctx, "executing http post for prismasdwan_element_bgp_peer")
	// Basic logging.
	tflog.Info(ctx, "performing resource create", map[string]any{
		"resource_name":               "prismasdwan_element_bgp_peer",
		"terraform_provider_function": "Create",
	})

	// Prepare input for the API endpoint.
	create_request := &sdwan_client.SdwanClientRequestResponse{}
	create_request.ResourceType = "prismasdwan_element_bgp_peer"
	create_request.Method = "POST"
	create_request.Path = "/sdwan/v2.6/api/sites/{site_id}/elements/{element_id}/bgppeers"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, plan.TfParameters)
	create_request.PathParameters = &params

	// Client that will perform the request.
	svc := sdwan_client.NewClient(r.client)

	// prepare request from state
	var body = &sdwan_schema.BGPPeerConfigScreenV2N6{}

	// copy from plan to body
	// copy_from_plan: body=body prefix=rsModel plan=plan properties=23
	tflog.Debug(ctx, "copy_from_plan body=body prefix=rsModel plan=plan")
	// property: name=_etag, type=INTEGER macro=copy_from_plan
	body.Etag = Int64ValueOrNil(plan.Etag)
	// property: name=_schema, type=INTEGER macro=copy_from_plan
	body.Schema = Int64ValueOrNil(plan.Schema)
	// property: name=advertise_default_route, type=BOOLEAN macro=copy_from_plan
	body.AdvertiseDefaultRoute = BoolValueOrNil(plan.AdvertiseDefaultRoute)
	// property: name=allow_v4_prefixes, type=BOOLEAN macro=copy_from_plan
	body.AllowV4Prefixes = BoolValueOrNil(plan.AllowV4Prefixes)
	// property: name=allow_v6_prefixes, type=BOOLEAN macro=copy_from_plan
	body.AllowV6Prefixes = BoolValueOrNil(plan.AllowV6Prefixes)
	// property: name=bgp_config, type=REFERENCE macro=copy_from_plan
	if plan.BgpConfig != nil {
		body.BgpConfig = &sdwan_schema.BGPConfig{}
		// copy_from_plan: body=body.BgpConfig prefix=rsModel plan=plan.BgpConfig properties=8
		tflog.Debug(ctx, "copy_from_plan body=body.BgpConfig prefix=rsModel plan=plan.BgpConfig")
		// property: name=adv_interval, type=INTEGER macro=copy_from_plan
		body.BgpConfig.AdvInterval = Int64ValueOrNil(plan.BgpConfig.AdvInterval)
		// property: name=hold_time, type=INTEGER macro=copy_from_plan
		body.BgpConfig.HoldTime = Int64ValueOrNil(plan.BgpConfig.HoldTime)
		// property: name=keepalive_time, type=INTEGER macro=copy_from_plan
		body.BgpConfig.KeepaliveTime = Int64ValueOrNil(plan.BgpConfig.KeepaliveTime)
		// property: name=local_as_num, type=STRING macro=copy_from_plan
		body.BgpConfig.LocalAsNum = StringValueOrNil(plan.BgpConfig.LocalAsNum)
		// property: name=md5_secret, type=STRING macro=copy_from_plan
		body.BgpConfig.Md5Secret = StringValueOrNil(plan.BgpConfig.Md5Secret)
		// property: name=multi_hop_limit, type=INTEGER macro=copy_from_plan
		body.BgpConfig.MultiHopLimit = Int64ValueOrNil(plan.BgpConfig.MultiHopLimit)
		// property: name=peer_auth_type, type=STRING macro=copy_from_plan
		body.BgpConfig.PeerAuthType = StringValueOrNil(plan.BgpConfig.PeerAuthType)
		// property: name=peer_retry_time, type=INTEGER macro=copy_from_plan
		body.BgpConfig.PeerRetryTime = Int64ValueOrNil(plan.BgpConfig.PeerRetryTime)
	}
	// property: name=description, type=STRING macro=copy_from_plan
	body.Description = StringValueOrNil(plan.Description)
	// property: name=id, type=STRING macro=copy_from_plan
	body.Id = StringValueOrNil(plan.Id)
	// property: name=name, type=STRING macro=copy_from_plan
	body.Name = StringValueOrNil(plan.Name)
	// property: name=peer_ip, type=STRING macro=copy_from_plan
	body.PeerIp = StringValueOrNil(plan.PeerIp)
	// property: name=peer_ip_v6, type=STRING macro=copy_from_plan
	body.PeerIpV6 = StringValueOrNil(plan.PeerIpV6)
	// property: name=peer_type, type=STRING macro=copy_from_plan
	body.PeerType = StringValueOrNil(plan.PeerType)
	// property: name=remote_as_num, type=STRING macro=copy_from_plan
	body.RemoteAsNum = StringValueOrNil(plan.RemoteAsNum)
	// property: name=route_aggregation, type=REFERENCE macro=copy_from_plan
	if plan.RouteAggregation != nil {
		body.RouteAggregation = &sdwan_schema.RouteAggregation{}
		// copy_from_plan: body=body.RouteAggregation prefix=rsModel plan=plan.RouteAggregation properties=4
		tflog.Debug(ctx, "copy_from_plan body=body.RouteAggregation prefix=rsModel plan=plan.RouteAggregation")
		// property: name=aggregate_prefixes, type=ARRAY_REFERENCE macro=copy_from_plan
		if plan.RouteAggregation.AggregatePrefixes == nil {
			body.RouteAggregation.AggregatePrefixes = nil
		} else if len(plan.RouteAggregation.AggregatePrefixes) == 0 {
			body.RouteAggregation.AggregatePrefixes = []sdwan_schema.AggregatePrefixes{}
		} else {
			body.RouteAggregation.AggregatePrefixes = make([]sdwan_schema.AggregatePrefixes, 0, len(plan.RouteAggregation.AggregatePrefixes))
			for varLoopAggregatePrefixesIndex, varLoopAggregatePrefixes := range plan.RouteAggregation.AggregatePrefixes {
				// add a new item
				body.RouteAggregation.AggregatePrefixes = append(body.RouteAggregation.AggregatePrefixes, sdwan_schema.AggregatePrefixes{})
				// copy_from_plan: body=body.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex] prefix=rsModel plan=varLoopAggregatePrefixes properties=2
				tflog.Debug(ctx, "copy_from_plan body=body.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex] prefix=rsModel plan=varLoopAggregatePrefixes")
				// property: name=ip_prefixes, type=ARRAY_PRIMITIVE macro=copy_from_plan
				body.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex].IpPrefixes = ListStringValueOrNil(ctx, varLoopAggregatePrefixes.IpPrefixes)
				// property: name=type, type=STRING macro=copy_from_plan
				body.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex].Type = StringValueOrNil(varLoopAggregatePrefixes.Type)
			}
		}
		// property: name=aggregate_type, type=STRING macro=copy_from_plan
		body.RouteAggregation.AggregateType = StringValueOrNil(plan.RouteAggregation.AggregateType)
		// property: name=ipv4_prefix_list_id, type=STRING macro=copy_from_plan
		body.RouteAggregation.Ipv4PrefixListId = StringValueOrNil(plan.RouteAggregation.Ipv4PrefixListId)
		// property: name=ipv6_prefix_list_id, type=STRING macro=copy_from_plan
		body.RouteAggregation.Ipv6PrefixListId = StringValueOrNil(plan.RouteAggregation.Ipv6PrefixListId)
	}
	// property: name=route_map_in_id, type=STRING macro=copy_from_plan
	body.RouteMapInId = StringValueOrNil(plan.RouteMapInId)
	// property: name=route_map_out_id, type=STRING macro=copy_from_plan
	body.RouteMapOutId = StringValueOrNil(plan.RouteMapOutId)
	// property: name=router_id, type=STRING macro=copy_from_plan
	body.RouterId = StringValueOrNil(plan.RouterId)
	// property: name=scope, type=STRING macro=copy_from_plan
	body.Scope = StringValueOrNil(plan.Scope)
	// property: name=shutdown, type=BOOLEAN macro=copy_from_plan
	body.Shutdown = BoolValueOrNil(plan.Shutdown)
	// property: name=tags, type=SET_PRIMITIVE macro=copy_from_plan
	body.Tags = SetStringValueOrNil(ctx, plan.Tags)
	// property: name=update_source, type=STRING macro=copy_from_plan
	body.UpdateSource = StringValueOrNil(plan.UpdateSource)
	// property: name=update_source_v6, type=STRING macro=copy_from_plan
	body.UpdateSourceV6 = StringValueOrNil(plan.UpdateSourceV6)
	// property: name=vrf_context_id, type=STRING macro=copy_from_plan
	body.VrfContextId = StringValueOrNil(plan.VrfContextId)

	// convert body to map
	json_body, err := json.Marshal(body)
	if err != nil {
		resp.Diagnostics.AddError("error marshaling struct BGPPeerConfigScreenV2N6 to JSON:", err.Error())
		return false
	}

	// process http json path
	request_body_string := string(json_body)
	// inject overrides
	tflog.Debug(ctx, "http json override: delete request_body_string::id")
	request_body_string, _ = sjson.Delete(request_body_string, "id")
	tflog.Debug(ctx, "http json override: delete request_body_string::_etag")
	request_body_string, _ = sjson.Delete(request_body_string, "_etag")
	tflog.Debug(ctx, "http json override: set request_body_string::_schema")
	request_body_string, _ = sjson.Set(request_body_string, "_schema", 0)
	// copy pointer
	create_request.RequestBody = &request_body_string

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, create_request)
	if create_request.ResponseErr != nil {
		tflog.Info(ctx, "create request failed for prismasdwan_element_bgp_peer", map[string]any{
			"terraform_provider_function": "Create",
			"resource_name":               "prismasdwan_element_bgp_peer",
			"path":                        create_request.FinalPath,
		})
		tflog.Debug(ctx, "create request failed for prismasdwan_element_bgp_peer", map[string]any{
			"terraform_provider_function": "Create",
			"resource_name":               "prismasdwan_element_bgp_peer",
			"path":                        create_request.FinalPath,
			"request":                     create_request.ToString(),
		})
		resp.Diagnostics.AddError("error creating prismasdwan_element_bgp_peer", (*create_request.ResponseErr).Error())
		return false
	}

	// process http json path
	response_body_string := string(*create_request.ResponseBytes)
	// inject overrides
	tflog.Debug(ctx, "http json override: delete response_body_string::_created_on_utc")
	response_body_string, _ = sjson.Delete(response_body_string, "_created_on_utc")
	tflog.Debug(ctx, "http json override: set response_body_string::_schema")
	response_body_string, _ = sjson.Set(response_body_string, "_schema", 0)

	// start copying attributes
	var ans sdwan_schema.BGPPeerConfigScreenV2N6
	// copy from json response
	json_err := json.Unmarshal([]byte(response_body_string), &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to BGPPeerConfigScreenV2N6 in create", json_err.Error())
		return false
	}

	// Create the Terraform ID.
	var idBuilder strings.Builder
	if ans.Id == nil {
		resp.Diagnostics.AddError("Undefined param required for ID", "Id")
		return false
	}
	// ID Format: Id:Param1=Value1:Param2=Value2:...:ParamN=ValueN
	if ans.Id != nil {
		idBuilder.WriteString(*ans.Id)
		for p, v := range *create_request.PathParameters {
			idBuilder.WriteString(IdSeparator)
			idBuilder.WriteString(p)
			idBuilder.WriteString("=")
			idBuilder.WriteString(*v)
		}
	}
	// set the tf id for the resource created
	state.Tfid = types.StringValue(idBuilder.String())
	state.TfParameters = plan.TfParameters
	tflog.Info(ctx, "created prismasdwan_element_bgp_peer with ID", map[string]any{"tfid": state.Tfid.ValueString()})

	// Store the answer to state. schema=BGPPeerConfigScreenV2N6
	// copy_to_state: state=state prefix=rsModel ans=ans properties=23
	tflog.Debug(ctx, "copy_to_state state=state prefix=rsModel ans=ans")
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=advertise_default_route, type=BOOLEAN macro=copy_to_state
	state.AdvertiseDefaultRoute = types.BoolPointerValue(ans.AdvertiseDefaultRoute)
	// property: name=allow_v4_prefixes, type=BOOLEAN macro=copy_to_state
	state.AllowV4Prefixes = types.BoolPointerValue(ans.AllowV4Prefixes)
	// property: name=allow_v6_prefixes, type=BOOLEAN macro=copy_to_state
	state.AllowV6Prefixes = types.BoolPointerValue(ans.AllowV6Prefixes)
	// property: name=bgp_config, type=REFERENCE macro=copy_to_state
	if ans.BgpConfig == nil {
		state.BgpConfig = nil
	} else {
		state.BgpConfig = &rsModelBGPConfig{}
		// copy_to_state: state=state.BgpConfig prefix=rsModel ans=ans.BgpConfig properties=8
		tflog.Debug(ctx, "copy_to_state state=state.BgpConfig prefix=rsModel ans=ans.BgpConfig")
		// property: name=adv_interval, type=INTEGER macro=copy_to_state
		state.BgpConfig.AdvInterval = types.Int64PointerValue(ans.BgpConfig.AdvInterval)
		// property: name=hold_time, type=INTEGER macro=copy_to_state
		state.BgpConfig.HoldTime = types.Int64PointerValue(ans.BgpConfig.HoldTime)
		// property: name=keepalive_time, type=INTEGER macro=copy_to_state
		state.BgpConfig.KeepaliveTime = types.Int64PointerValue(ans.BgpConfig.KeepaliveTime)
		// property: name=local_as_num, type=STRING macro=copy_to_state
		state.BgpConfig.LocalAsNum = types.StringPointerValue(ans.BgpConfig.LocalAsNum)
		// property: name=md5_secret, type=STRING macro=copy_to_state
		state.BgpConfig.Md5Secret = types.StringPointerValue(plan.BgpConfig.Md5Secret.ValueStringPointer())
		// this property is sensitive and will be stored in the state's internal key name
		state.BgpConfig.Md5SecretInternalKeyName = types.StringValue(GenerateRandomString(16))
		// store value if needed
		if !state.BgpConfig.Md5Secret.IsNull() {
			encryptedMd5Secret, _ := Encrypt([]byte(state.BgpConfig.Md5Secret.String()))
			resp.Private.SetKey(ctx, state.BgpConfig.Md5SecretInternalKeyName.String(), []byte(encryptedMd5Secret))
		}
		// property: name=multi_hop_limit, type=INTEGER macro=copy_to_state
		state.BgpConfig.MultiHopLimit = types.Int64PointerValue(ans.BgpConfig.MultiHopLimit)
		// property: name=peer_auth_type, type=STRING macro=copy_to_state
		state.BgpConfig.PeerAuthType = types.StringPointerValue(ans.BgpConfig.PeerAuthType)
		// property: name=peer_retry_time, type=INTEGER macro=copy_to_state
		state.BgpConfig.PeerRetryTime = types.Int64PointerValue(ans.BgpConfig.PeerRetryTime)
	}
	// property: name=description, type=STRING macro=copy_to_state
	state.Description = types.StringPointerValue(ans.Description)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=name, type=STRING macro=copy_to_state
	state.Name = types.StringPointerValue(ans.Name)
	// property: name=peer_ip, type=STRING macro=copy_to_state
	state.PeerIp = types.StringPointerValue(ans.PeerIp)
	// property: name=peer_ip_v6, type=STRING macro=copy_to_state
	state.PeerIpV6 = types.StringPointerValue(ans.PeerIpV6)
	// property: name=peer_type, type=STRING macro=copy_to_state
	state.PeerType = types.StringPointerValue(ans.PeerType)
	// property: name=remote_as_num, type=STRING macro=copy_to_state
	state.RemoteAsNum = types.StringPointerValue(ans.RemoteAsNum)
	// property: name=route_aggregation, type=REFERENCE macro=copy_to_state
	if ans.RouteAggregation == nil {
		state.RouteAggregation = nil
	} else {
		state.RouteAggregation = &rsModelRouteAggregation{}
		// copy_to_state: state=state.RouteAggregation prefix=rsModel ans=ans.RouteAggregation properties=4
		tflog.Debug(ctx, "copy_to_state state=state.RouteAggregation prefix=rsModel ans=ans.RouteAggregation")
		// property: name=aggregate_prefixes, type=ARRAY_REFERENCE macro=copy_to_state
		if ans.RouteAggregation.AggregatePrefixes == nil {
			state.RouteAggregation.AggregatePrefixes = nil
		} else if len(ans.RouteAggregation.AggregatePrefixes) == 0 {
			state.RouteAggregation.AggregatePrefixes = []rsModelAggregatePrefixes{}
		} else {
			state.RouteAggregation.AggregatePrefixes = make([]rsModelAggregatePrefixes, 0, len(ans.RouteAggregation.AggregatePrefixes))
			for varLoopAggregatePrefixesIndex, varLoopAggregatePrefixes := range ans.RouteAggregation.AggregatePrefixes {
				// add a new item
				state.RouteAggregation.AggregatePrefixes = append(state.RouteAggregation.AggregatePrefixes, rsModelAggregatePrefixes{})
				// copy_to_state: state=state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex] prefix=rsModel ans=varLoopAggregatePrefixes properties=2
				tflog.Debug(ctx, "copy_to_state state=state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex] prefix=rsModel ans=varLoopAggregatePrefixes")
				// property: name=ip_prefixes, type=ARRAY_PRIMITIVE macro=copy_to_state
				varIpPrefixes, errIpPrefixes := types.ListValueFrom(ctx, types.StringType, varLoopAggregatePrefixes.IpPrefixes)
				state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex].IpPrefixes = varIpPrefixes
				resp.Diagnostics.Append(errIpPrefixes.Errors()...)
				// property: name=type, type=STRING macro=copy_to_state
				state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex].Type = types.StringPointerValue(varLoopAggregatePrefixes.Type)
			}
		}
		// property: name=aggregate_type, type=STRING macro=copy_to_state
		state.RouteAggregation.AggregateType = types.StringPointerValue(ans.RouteAggregation.AggregateType)
		// property: name=ipv4_prefix_list_id, type=STRING macro=copy_to_state
		state.RouteAggregation.Ipv4PrefixListId = types.StringPointerValue(ans.RouteAggregation.Ipv4PrefixListId)
		// property: name=ipv6_prefix_list_id, type=STRING macro=copy_to_state
		state.RouteAggregation.Ipv6PrefixListId = types.StringPointerValue(ans.RouteAggregation.Ipv6PrefixListId)
	}
	// property: name=route_map_in_id, type=STRING macro=copy_to_state
	state.RouteMapInId = types.StringPointerValue(ans.RouteMapInId)
	// property: name=route_map_out_id, type=STRING macro=copy_to_state
	state.RouteMapOutId = types.StringPointerValue(ans.RouteMapOutId)
	// property: name=router_id, type=STRING macro=copy_to_state
	state.RouterId = types.StringPointerValue(ans.RouterId)
	// property: name=scope, type=STRING macro=copy_to_state
	state.Scope = types.StringPointerValue(ans.Scope)
	// property: name=shutdown, type=BOOLEAN macro=copy_to_state
	state.Shutdown = types.BoolPointerValue(ans.Shutdown)
	// property: name=tags, type=SET_PRIMITIVE macro=copy_to_state
	varTags, errTags := types.SetValueFrom(ctx, types.StringType, ans.Tags)
	state.Tags = varTags
	resp.Diagnostics.Append(errTags.Errors()...)
	// property: name=update_source, type=STRING macro=copy_to_state
	state.UpdateSource = types.StringPointerValue(ans.UpdateSource)
	// property: name=update_source_v6, type=STRING macro=copy_to_state
	state.UpdateSourceV6 = types.StringPointerValue(ans.UpdateSourceV6)
	// property: name=vrf_context_id, type=STRING macro=copy_to_state
	state.VrfContextId = types.StringPointerValue(ans.VrfContextId)
	return true
}

func (r *elementBgpPeerResource) doGet(ctx context.Context, state *rsModelBGPPeerConfigScreenV2N6, savestate *rsModelBGPPeerConfigScreenV2N6, State *tfsdk.State, resp *resource.ReadResponse) bool {
	// Basic logging.
	tfid := savestate.Tfid.ValueString()
	tflog.Info(ctx, "performing resource read", map[string]any{
		"terraform_provider_function": "Read",
		"resource_name":               "prismasdwan_element_bgp_peer",
		"tfid":                        tfid,
	})

	tokens := strings.Split(tfid, IdSeparator)
	if len(tokens) < 3 {
		resp.Diagnostics.AddError("error in prismasdwan_element_bgp_peer ID format", "Expected 3 tokens")
		return false
	}

	// Prepare to read the config.
	svc := sdwan_client.NewClient(r.client)

	// Prepare input for the API endpoint.
	read_request := &sdwan_client.SdwanClientRequestResponse{}
	read_request.ResourceType = "prismasdwan_element_bgp_peer"
	read_request.Method = "GET"
	read_request.Path = "/sdwan/v2.6/api/sites/{site_id}/elements/{element_id}/bgppeers/{bgp_peer_id}"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, savestate.TfParameters)
	read_request.PathParameters = &params
	// add last parameter as ObjectID
	(*read_request.PathParameters)["bgp_peer_id"] = &tokens[0]
	// add other parameters by splitting on `=`
	for _, token := range tokens[1:] {
		param := strings.Split(token, "=")
		(*read_request.PathParameters)[param[0]] = &param[1]
	}

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, read_request)
	if read_request.ResponseErr != nil {
		if IsObjectNotFound(*read_request.ResponseErr) {
			State.RemoveResource(ctx)
		} else if r.GetHttpStatusCode(read_request) == 404 {
			State.RemoveResource(ctx)
		} else {
			tflog.Info(ctx, "read request failed for prismasdwan_element_bgp_peer", map[string]any{
				"terraform_provider_function": "Read",
				"resource_name":               "prismasdwan_element_bgp_peer",
				"path":                        read_request.FinalPath,
				"request":                     read_request.ToString(),
			})
			resp.Diagnostics.AddError("error reading prismasdwan_element_bgp_peer from sdwan servers", (*read_request.ResponseErr).Error())
		}
		return false
	}

	// process http json path
	response_body_string := string(*read_request.ResponseBytes)
	// inject overrides
	tflog.Debug(ctx, "http json override: delete response_body_string::_created_on_utc")
	response_body_string, _ = sjson.Delete(response_body_string, "_created_on_utc")
	tflog.Debug(ctx, "http json override: set response_body_string::_schema")
	response_body_string, _ = sjson.Set(response_body_string, "_schema", 0)

	// Store the answer to state. schema=BGPPeerConfigScreenV2N6
	state.Tfid = savestate.Tfid
	// copy parameters from savestate as they are
	if savestate.TfParameters.IsNull() {
		state.TfParameters = types.MapNull(types.StringType)
	} else {
		state.TfParameters = savestate.TfParameters
	}
	// start copying attributes
	var ans sdwan_schema.BGPPeerConfigScreenV2N6
	// copy from json response
	json_err := json.Unmarshal([]byte(response_body_string), &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to BGPPeerConfigScreenV2N6 in read", json_err.Error())
		return false
	}
	// lets copy all items into state
	// copy_to_state: state=state prefix=rsModel ans=ans properties=23
	tflog.Debug(ctx, "copy_to_state state=state prefix=rsModel ans=ans")
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=advertise_default_route, type=BOOLEAN macro=copy_to_state
	state.AdvertiseDefaultRoute = types.BoolPointerValue(ans.AdvertiseDefaultRoute)
	// property: name=allow_v4_prefixes, type=BOOLEAN macro=copy_to_state
	state.AllowV4Prefixes = types.BoolPointerValue(ans.AllowV4Prefixes)
	// property: name=allow_v6_prefixes, type=BOOLEAN macro=copy_to_state
	state.AllowV6Prefixes = types.BoolPointerValue(ans.AllowV6Prefixes)
	// property: name=bgp_config, type=REFERENCE macro=copy_to_state
	if ans.BgpConfig == nil {
		state.BgpConfig = nil
	} else {
		state.BgpConfig = &rsModelBGPConfig{}
		// copy_to_state: state=state.BgpConfig prefix=rsModel ans=ans.BgpConfig properties=8
		tflog.Debug(ctx, "copy_to_state state=state.BgpConfig prefix=rsModel ans=ans.BgpConfig")
		// property: name=adv_interval, type=INTEGER macro=copy_to_state
		state.BgpConfig.AdvInterval = types.Int64PointerValue(ans.BgpConfig.AdvInterval)
		// property: name=hold_time, type=INTEGER macro=copy_to_state
		state.BgpConfig.HoldTime = types.Int64PointerValue(ans.BgpConfig.HoldTime)
		// property: name=keepalive_time, type=INTEGER macro=copy_to_state
		state.BgpConfig.KeepaliveTime = types.Int64PointerValue(ans.BgpConfig.KeepaliveTime)
		// property: name=local_as_num, type=STRING macro=copy_to_state
		state.BgpConfig.LocalAsNum = types.StringPointerValue(ans.BgpConfig.LocalAsNum)
		// property: name=md5_secret, type=STRING macro=copy_to_state
		encryptedMd5SecretKeyName := state.BgpConfig.Md5SecretInternalKeyName.String()
		encryptedMd5SecretValueBytes, _ := resp.Private.GetKey(ctx, encryptedMd5SecretKeyName)
		if encryptedMd5SecretValueBytes != nil {
			decryptedMd5Secret, _ := Decrypt(string(encryptedMd5SecretValueBytes))
			state.BgpConfig.Md5Secret = types.StringValue(decryptedMd5Secret)
		}
		// property: name=multi_hop_limit, type=INTEGER macro=copy_to_state
		state.BgpConfig.MultiHopLimit = types.Int64PointerValue(ans.BgpConfig.MultiHopLimit)
		// property: name=peer_auth_type, type=STRING macro=copy_to_state
		state.BgpConfig.PeerAuthType = types.StringPointerValue(ans.BgpConfig.PeerAuthType)
		// property: name=peer_retry_time, type=INTEGER macro=copy_to_state
		state.BgpConfig.PeerRetryTime = types.Int64PointerValue(ans.BgpConfig.PeerRetryTime)
	}
	// property: name=description, type=STRING macro=copy_to_state
	state.Description = types.StringPointerValue(ans.Description)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=name, type=STRING macro=copy_to_state
	state.Name = types.StringPointerValue(ans.Name)
	// property: name=peer_ip, type=STRING macro=copy_to_state
	state.PeerIp = types.StringPointerValue(ans.PeerIp)
	// property: name=peer_ip_v6, type=STRING macro=copy_to_state
	state.PeerIpV6 = types.StringPointerValue(ans.PeerIpV6)
	// property: name=peer_type, type=STRING macro=copy_to_state
	state.PeerType = types.StringPointerValue(ans.PeerType)
	// property: name=remote_as_num, type=STRING macro=copy_to_state
	state.RemoteAsNum = types.StringPointerValue(ans.RemoteAsNum)
	// property: name=route_aggregation, type=REFERENCE macro=copy_to_state
	if ans.RouteAggregation == nil {
		state.RouteAggregation = nil
	} else {
		state.RouteAggregation = &rsModelRouteAggregation{}
		// copy_to_state: state=state.RouteAggregation prefix=rsModel ans=ans.RouteAggregation properties=4
		tflog.Debug(ctx, "copy_to_state state=state.RouteAggregation prefix=rsModel ans=ans.RouteAggregation")
		// property: name=aggregate_prefixes, type=ARRAY_REFERENCE macro=copy_to_state
		if ans.RouteAggregation.AggregatePrefixes == nil {
			state.RouteAggregation.AggregatePrefixes = nil
		} else if len(ans.RouteAggregation.AggregatePrefixes) == 0 {
			state.RouteAggregation.AggregatePrefixes = []rsModelAggregatePrefixes{}
		} else {
			state.RouteAggregation.AggregatePrefixes = make([]rsModelAggregatePrefixes, 0, len(ans.RouteAggregation.AggregatePrefixes))
			for varLoopAggregatePrefixesIndex, varLoopAggregatePrefixes := range ans.RouteAggregation.AggregatePrefixes {
				// add a new item
				state.RouteAggregation.AggregatePrefixes = append(state.RouteAggregation.AggregatePrefixes, rsModelAggregatePrefixes{})
				// copy_to_state: state=state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex] prefix=rsModel ans=varLoopAggregatePrefixes properties=2
				tflog.Debug(ctx, "copy_to_state state=state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex] prefix=rsModel ans=varLoopAggregatePrefixes")
				// property: name=ip_prefixes, type=ARRAY_PRIMITIVE macro=copy_to_state
				varIpPrefixes, errIpPrefixes := types.ListValueFrom(ctx, types.StringType, varLoopAggregatePrefixes.IpPrefixes)
				state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex].IpPrefixes = varIpPrefixes
				resp.Diagnostics.Append(errIpPrefixes.Errors()...)
				// property: name=type, type=STRING macro=copy_to_state
				state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex].Type = types.StringPointerValue(varLoopAggregatePrefixes.Type)
			}
		}
		// property: name=aggregate_type, type=STRING macro=copy_to_state
		state.RouteAggregation.AggregateType = types.StringPointerValue(ans.RouteAggregation.AggregateType)
		// property: name=ipv4_prefix_list_id, type=STRING macro=copy_to_state
		state.RouteAggregation.Ipv4PrefixListId = types.StringPointerValue(ans.RouteAggregation.Ipv4PrefixListId)
		// property: name=ipv6_prefix_list_id, type=STRING macro=copy_to_state
		state.RouteAggregation.Ipv6PrefixListId = types.StringPointerValue(ans.RouteAggregation.Ipv6PrefixListId)
	}
	// property: name=route_map_in_id, type=STRING macro=copy_to_state
	state.RouteMapInId = types.StringPointerValue(ans.RouteMapInId)
	// property: name=route_map_out_id, type=STRING macro=copy_to_state
	state.RouteMapOutId = types.StringPointerValue(ans.RouteMapOutId)
	// property: name=router_id, type=STRING macro=copy_to_state
	state.RouterId = types.StringPointerValue(ans.RouterId)
	// property: name=scope, type=STRING macro=copy_to_state
	state.Scope = types.StringPointerValue(ans.Scope)
	// property: name=shutdown, type=BOOLEAN macro=copy_to_state
	state.Shutdown = types.BoolPointerValue(ans.Shutdown)
	// property: name=tags, type=SET_PRIMITIVE macro=copy_to_state
	varTags, errTags := types.SetValueFrom(ctx, types.StringType, ans.Tags)
	state.Tags = varTags
	resp.Diagnostics.Append(errTags.Errors()...)
	// property: name=update_source, type=STRING macro=copy_to_state
	state.UpdateSource = types.StringPointerValue(ans.UpdateSource)
	// property: name=update_source_v6, type=STRING macro=copy_to_state
	state.UpdateSourceV6 = types.StringPointerValue(ans.UpdateSourceV6)
	// property: name=vrf_context_id, type=STRING macro=copy_to_state
	state.VrfContextId = types.StringPointerValue(ans.VrfContextId)
	return true
}

func (r *elementBgpPeerResource) doPut(ctx context.Context, plan *rsModelBGPPeerConfigScreenV2N6, state *rsModelBGPPeerConfigScreenV2N6, State *tfsdk.State, resp *resource.UpdateResponse) bool {
	state_tfid := state.Tfid.ValueString()
	plan_tfid := plan.Tfid.ValueString()
	// Basic logging.
	tflog.Info(ctx, "performing resource update", map[string]any{
		"terraform_provider_function": "Update",
		"resource_name":               "prismasdwan_element_bgp_peer",
		"state_tfid":                  state_tfid,
		"plan_tfid":                   plan_tfid,
	})

	// both TFID must be SAME!!!
	if state_tfid != plan_tfid {
		resp.Diagnostics.AddError("error updating prismasdwan_element_bgp_peer", "state and plan TFID do not match")
		return false
	}

	// split tokens
	tokens := strings.Split(state_tfid, IdSeparator)
	if len(tokens) < 3 {
		resp.Diagnostics.AddError("error in prismasdwan_element_bgp_peer ID format", "Expected 3 tokens")
		return false
	}

	// Prepare input for the API endpoint.
	put_request := &sdwan_client.SdwanClientRequestResponse{}
	put_request.ResourceType = "prismasdwan_element_bgp_peer"
	put_request.Method = "PUT"
	put_request.Path = "/sdwan/v2.6/api/sites/{site_id}/elements/{element_id}/bgppeers/{bgp_peer_id}"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, state.TfParameters)
	put_request.PathParameters = &params
	// add last parameter as ObjectID
	(*put_request.PathParameters)["bgp_peer_id"] = &tokens[0]
	// add other parameters by splitting on `=`
	for _, token := range tokens[1:] {
		param := strings.Split(token, "=")
		(*put_request.PathParameters)[param[0]] = &param[1]
	}

	// Client that will perform the request.
	svc := sdwan_client.NewClient(r.client)

	// prepare request from state
	var body = &sdwan_schema.BGPPeerConfigScreenV2N6{}

	// now we create the JSON request from the state/plan created by TF
	// below copy code generated from macro copy_from_plan_or_state
	// copy_from_plan_or_state: body=body prefix=rsModel state=state plan=plan properties=23
	tflog.Debug(ctx, "copy_from_plan_or_state body=body prefix=rsModel state=state plan=plan")
	// property: name=_etag, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.Etag = ValueInt64PointerFromPlanOrState(plan.Etag, state.Etag)
	} else {
		body.Etag = Int64ValueOrNil(plan.Etag)
	}
	// property: name=_schema, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.Schema = ValueInt64PointerFromPlanOrState(plan.Schema, state.Schema)
	} else {
		body.Schema = Int64ValueOrNil(plan.Schema)
	}
	// property: name=advertise_default_route, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.AdvertiseDefaultRoute = ValueBoolPointerFromPlanOrState(plan.AdvertiseDefaultRoute, state.AdvertiseDefaultRoute)
	} else {
		body.AdvertiseDefaultRoute = BoolValueOrNil(plan.AdvertiseDefaultRoute)
	}
	// property: name=allow_v4_prefixes, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.AllowV4Prefixes = ValueBoolPointerFromPlanOrState(plan.AllowV4Prefixes, state.AllowV4Prefixes)
	} else {
		body.AllowV4Prefixes = BoolValueOrNil(plan.AllowV4Prefixes)
	}
	// property: name=allow_v6_prefixes, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.AllowV6Prefixes = ValueBoolPointerFromPlanOrState(plan.AllowV6Prefixes, state.AllowV6Prefixes)
	} else {
		body.AllowV6Prefixes = BoolValueOrNil(plan.AllowV6Prefixes)
	}
	// property: name=bgp_config, type=REFERENCE macro=copy_from_plan_or_state
	if plan.BgpConfig == nil {
		body.BgpConfig = nil
	} else {
		body.BgpConfig = &sdwan_schema.BGPConfig{}
		// copy_from_plan_or_state: body=body.BgpConfig prefix=rsModel state=state.BgpConfig plan=plan.BgpConfig properties=8
		tflog.Debug(ctx, "copy_from_plan_or_state body=body.BgpConfig prefix=rsModel state=state.BgpConfig plan=plan.BgpConfig")
		// property: name=adv_interval, type=INTEGER macro=copy_from_plan_or_state
		if state.BgpConfig != nil {
			body.BgpConfig.AdvInterval = ValueInt64PointerFromPlanOrState(plan.BgpConfig.AdvInterval, state.BgpConfig.AdvInterval)
		} else {
			body.BgpConfig.AdvInterval = Int64ValueOrNil(plan.BgpConfig.AdvInterval)
		}
		// property: name=hold_time, type=INTEGER macro=copy_from_plan_or_state
		if state.BgpConfig != nil {
			body.BgpConfig.HoldTime = ValueInt64PointerFromPlanOrState(plan.BgpConfig.HoldTime, state.BgpConfig.HoldTime)
		} else {
			body.BgpConfig.HoldTime = Int64ValueOrNil(plan.BgpConfig.HoldTime)
		}
		// property: name=keepalive_time, type=INTEGER macro=copy_from_plan_or_state
		if state.BgpConfig != nil {
			body.BgpConfig.KeepaliveTime = ValueInt64PointerFromPlanOrState(plan.BgpConfig.KeepaliveTime, state.BgpConfig.KeepaliveTime)
		} else {
			body.BgpConfig.KeepaliveTime = Int64ValueOrNil(plan.BgpConfig.KeepaliveTime)
		}
		// property: name=local_as_num, type=STRING macro=copy_from_plan_or_state
		if state.BgpConfig != nil {
			body.BgpConfig.LocalAsNum = ValueStringPointerFromPlanOrState(plan.BgpConfig.LocalAsNum, state.BgpConfig.LocalAsNum)
		} else {
			body.BgpConfig.LocalAsNum = StringValueOrNil(plan.BgpConfig.LocalAsNum)
		}
		// property: name=md5_secret, type=STRING macro=copy_from_plan_or_state
		if state.BgpConfig != nil {
			body.BgpConfig.Md5Secret = ValueStringPointerFromPlanOrState(plan.BgpConfig.Md5Secret, state.BgpConfig.Md5Secret)
		} else {
			body.BgpConfig.Md5Secret = StringValueOrNil(plan.BgpConfig.Md5Secret)
		}
		// property: name=multi_hop_limit, type=INTEGER macro=copy_from_plan_or_state
		if state.BgpConfig != nil {
			body.BgpConfig.MultiHopLimit = ValueInt64PointerFromPlanOrState(plan.BgpConfig.MultiHopLimit, state.BgpConfig.MultiHopLimit)
		} else {
			body.BgpConfig.MultiHopLimit = Int64ValueOrNil(plan.BgpConfig.MultiHopLimit)
		}
		// property: name=peer_auth_type, type=STRING macro=copy_from_plan_or_state
		if state.BgpConfig != nil {
			body.BgpConfig.PeerAuthType = ValueStringPointerFromPlanOrState(plan.BgpConfig.PeerAuthType, state.BgpConfig.PeerAuthType)
		} else {
			body.BgpConfig.PeerAuthType = StringValueOrNil(plan.BgpConfig.PeerAuthType)
		}
		// property: name=peer_retry_time, type=INTEGER macro=copy_from_plan_or_state
		if state.BgpConfig != nil {
			body.BgpConfig.PeerRetryTime = ValueInt64PointerFromPlanOrState(plan.BgpConfig.PeerRetryTime, state.BgpConfig.PeerRetryTime)
		} else {
			body.BgpConfig.PeerRetryTime = Int64ValueOrNil(plan.BgpConfig.PeerRetryTime)
		}
	}
	// property: name=description, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Description = ValueStringPointerFromPlanOrState(plan.Description, state.Description)
	} else {
		body.Description = StringValueOrNil(plan.Description)
	}
	// property: name=id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Id = ValueStringPointerFromPlanOrState(plan.Id, state.Id)
	} else {
		body.Id = StringValueOrNil(plan.Id)
	}
	// property: name=name, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Name = ValueStringPointerFromPlanOrState(plan.Name, state.Name)
	} else {
		body.Name = StringValueOrNil(plan.Name)
	}
	// property: name=peer_ip, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.PeerIp = ValueStringPointerFromPlanOrState(plan.PeerIp, state.PeerIp)
	} else {
		body.PeerIp = StringValueOrNil(plan.PeerIp)
	}
	// property: name=peer_ip_v6, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.PeerIpV6 = ValueStringPointerFromPlanOrState(plan.PeerIpV6, state.PeerIpV6)
	} else {
		body.PeerIpV6 = StringValueOrNil(plan.PeerIpV6)
	}
	// property: name=peer_type, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.PeerType = ValueStringPointerFromPlanOrState(plan.PeerType, state.PeerType)
	} else {
		body.PeerType = StringValueOrNil(plan.PeerType)
	}
	// property: name=remote_as_num, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.RemoteAsNum = ValueStringPointerFromPlanOrState(plan.RemoteAsNum, state.RemoteAsNum)
	} else {
		body.RemoteAsNum = StringValueOrNil(plan.RemoteAsNum)
	}
	// property: name=route_aggregation, type=REFERENCE macro=copy_from_plan_or_state
	if plan.RouteAggregation == nil {
		body.RouteAggregation = nil
	} else {
		body.RouteAggregation = &sdwan_schema.RouteAggregation{}
		// copy_from_plan_or_state: body=body.RouteAggregation prefix=rsModel state=state.RouteAggregation plan=plan.RouteAggregation properties=4
		tflog.Debug(ctx, "copy_from_plan_or_state body=body.RouteAggregation prefix=rsModel state=state.RouteAggregation plan=plan.RouteAggregation")
		// property: name=aggregate_prefixes, type=ARRAY_REFERENCE macro=copy_from_plan_or_state
		if plan.RouteAggregation.AggregatePrefixes == nil && (state.RouteAggregation == nil || state.RouteAggregation.AggregatePrefixes == nil) {
			body.RouteAggregation.AggregatePrefixes = nil
		} else if len(plan.RouteAggregation.AggregatePrefixes) == 0 && (state.RouteAggregation == nil || len(state.RouteAggregation.AggregatePrefixes) == 0) {
			body.RouteAggregation.AggregatePrefixes = []sdwan_schema.AggregatePrefixes{}
		} else if len(plan.RouteAggregation.AggregatePrefixes) != 0 || (state.RouteAggregation != nil && len(state.RouteAggregation.AggregatePrefixes) != 0) {
			AggregatePrefixesToUse := plan.RouteAggregation.AggregatePrefixes
			if len(plan.RouteAggregation.AggregatePrefixes) == 0 {
				AggregatePrefixesToUse = state.RouteAggregation.AggregatePrefixes
			}
			body.RouteAggregation.AggregatePrefixes = make([]sdwan_schema.AggregatePrefixes, 0, len(AggregatePrefixesToUse))
			for varLoopAggregatePrefixesIndex, varLoopAggregatePrefixes := range AggregatePrefixesToUse {
				// add a new item
				body.RouteAggregation.AggregatePrefixes = append(body.RouteAggregation.AggregatePrefixes, sdwan_schema.AggregatePrefixes{})
				// since we have chosen to stick with either the plan or state, we need to simply copy child properties
				// copy_from_plan: body=body.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex] prefix=rsModel plan=varLoopAggregatePrefixes properties=2
				tflog.Debug(ctx, "copy_from_plan body=body.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex] prefix=rsModel plan=varLoopAggregatePrefixes")
				// property: name=ip_prefixes, type=ARRAY_PRIMITIVE macro=copy_from_plan
				body.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex].IpPrefixes = ListStringValueOrNil(ctx, varLoopAggregatePrefixes.IpPrefixes)
				// property: name=type, type=STRING macro=copy_from_plan
				body.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex].Type = StringValueOrNil(varLoopAggregatePrefixes.Type)
			}
		}
		// property: name=aggregate_type, type=STRING macro=copy_from_plan_or_state
		if state.RouteAggregation != nil {
			body.RouteAggregation.AggregateType = ValueStringPointerFromPlanOrState(plan.RouteAggregation.AggregateType, state.RouteAggregation.AggregateType)
		} else {
			body.RouteAggregation.AggregateType = StringValueOrNil(plan.RouteAggregation.AggregateType)
		}
		// property: name=ipv4_prefix_list_id, type=STRING macro=copy_from_plan_or_state
		if state.RouteAggregation != nil {
			body.RouteAggregation.Ipv4PrefixListId = ValueStringPointerFromPlanOrState(plan.RouteAggregation.Ipv4PrefixListId, state.RouteAggregation.Ipv4PrefixListId)
		} else {
			body.RouteAggregation.Ipv4PrefixListId = StringValueOrNil(plan.RouteAggregation.Ipv4PrefixListId)
		}
		// property: name=ipv6_prefix_list_id, type=STRING macro=copy_from_plan_or_state
		if state.RouteAggregation != nil {
			body.RouteAggregation.Ipv6PrefixListId = ValueStringPointerFromPlanOrState(plan.RouteAggregation.Ipv6PrefixListId, state.RouteAggregation.Ipv6PrefixListId)
		} else {
			body.RouteAggregation.Ipv6PrefixListId = StringValueOrNil(plan.RouteAggregation.Ipv6PrefixListId)
		}
	}
	// property: name=route_map_in_id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.RouteMapInId = ValueStringPointerFromPlanOrState(plan.RouteMapInId, state.RouteMapInId)
	} else {
		body.RouteMapInId = StringValueOrNil(plan.RouteMapInId)
	}
	// property: name=route_map_out_id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.RouteMapOutId = ValueStringPointerFromPlanOrState(plan.RouteMapOutId, state.RouteMapOutId)
	} else {
		body.RouteMapOutId = StringValueOrNil(plan.RouteMapOutId)
	}
	// property: name=router_id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.RouterId = ValueStringPointerFromPlanOrState(plan.RouterId, state.RouterId)
	} else {
		body.RouterId = StringValueOrNil(plan.RouterId)
	}
	// property: name=scope, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Scope = ValueStringPointerFromPlanOrState(plan.Scope, state.Scope)
	} else {
		body.Scope = StringValueOrNil(plan.Scope)
	}
	// property: name=shutdown, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.Shutdown = ValueBoolPointerFromPlanOrState(plan.Shutdown, state.Shutdown)
	} else {
		body.Shutdown = BoolValueOrNil(plan.Shutdown)
	}
	// property: name=tags, type=SET_PRIMITIVE macro=copy_from_plan_or_state
	body.Tags = SetStringValueOrNil(ctx, plan.Tags)
	// property: name=update_source, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.UpdateSource = ValueStringPointerFromPlanOrState(plan.UpdateSource, state.UpdateSource)
	} else {
		body.UpdateSource = StringValueOrNil(plan.UpdateSource)
	}
	// property: name=update_source_v6, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.UpdateSourceV6 = ValueStringPointerFromPlanOrState(plan.UpdateSourceV6, state.UpdateSourceV6)
	} else {
		body.UpdateSourceV6 = StringValueOrNil(plan.UpdateSourceV6)
	}
	// property: name=vrf_context_id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.VrfContextId = ValueStringPointerFromPlanOrState(plan.VrfContextId, state.VrfContextId)
	} else {
		body.VrfContextId = StringValueOrNil(plan.VrfContextId)
	}

	// convert body to map
	json_body, err := json.Marshal(body)
	if err != nil {
		resp.Diagnostics.AddError("error marshaling struct BGPPeerConfigScreenV2N6 to JSON:", err.Error())
		return false
	}

	// process http json path
	request_body_string := string(json_body)
	// copy pointer
	put_request.RequestBody = &request_body_string

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, put_request)
	if put_request.ResponseErr != nil {
		if IsObjectNotFound(*put_request.ResponseErr) {
			State.RemoveResource(ctx)
		} else if r.GetHttpStatusCode(put_request) == 404 {
			State.RemoveResource(ctx)
		} else {
			tflog.Info(ctx, "update request failed for prismasdwan_element_bgp_peer", map[string]any{
				"terraform_provider_function": "Update",
				"resource_name":               "prismasdwan_element_bgp_peer",
				"path":                        put_request.FinalPath,
			})
			tflog.Debug(ctx, "update request failed for prismasdwan_element_bgp_peer", map[string]any{
				"terraform_provider_function": "Update",
				"resource_name":               "prismasdwan_element_bgp_peer",
				"path":                        put_request.FinalPath,
				"request":                     put_request.ToString(),
			})
			resp.Diagnostics.AddError("error updating prismasdwan_element_bgp_peer", (*put_request.ResponseErr).Error())
		}
		return false
	}

	// process http json path
	response_body_string := string(*put_request.ResponseBytes)
	// inject overrides
	tflog.Debug(ctx, "http json override: delete response_body_string::_created_on_utc")
	response_body_string, _ = sjson.Delete(response_body_string, "_created_on_utc")
	tflog.Debug(ctx, "http json override: set response_body_string::_schema")
	response_body_string, _ = sjson.Set(response_body_string, "_schema", 0)

	// start copying attributes
	var ans sdwan_schema.BGPPeerConfigScreenV2N6
	// copy from json response
	json_err := json.Unmarshal([]byte(response_body_string), &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to BGPPeerConfigScreenV2N6 in update", json_err.Error())
		return false
	}

	// Store the answer to state. schema=BGPPeerConfigScreenV2N6
	// copy_to_state: state=state prefix=rsModel ans=ans properties=23
	tflog.Debug(ctx, "copy_to_state state=state prefix=rsModel ans=ans")
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=advertise_default_route, type=BOOLEAN macro=copy_to_state
	state.AdvertiseDefaultRoute = types.BoolPointerValue(ans.AdvertiseDefaultRoute)
	// property: name=allow_v4_prefixes, type=BOOLEAN macro=copy_to_state
	state.AllowV4Prefixes = types.BoolPointerValue(ans.AllowV4Prefixes)
	// property: name=allow_v6_prefixes, type=BOOLEAN macro=copy_to_state
	state.AllowV6Prefixes = types.BoolPointerValue(ans.AllowV6Prefixes)
	// property: name=bgp_config, type=REFERENCE macro=copy_to_state
	if ans.BgpConfig == nil {
		state.BgpConfig = nil
	} else {
		state.BgpConfig = &rsModelBGPConfig{}
		// copy_to_state: state=state.BgpConfig prefix=rsModel ans=ans.BgpConfig properties=8
		tflog.Debug(ctx, "copy_to_state state=state.BgpConfig prefix=rsModel ans=ans.BgpConfig")
		// property: name=adv_interval, type=INTEGER macro=copy_to_state
		state.BgpConfig.AdvInterval = types.Int64PointerValue(ans.BgpConfig.AdvInterval)
		// property: name=hold_time, type=INTEGER macro=copy_to_state
		state.BgpConfig.HoldTime = types.Int64PointerValue(ans.BgpConfig.HoldTime)
		// property: name=keepalive_time, type=INTEGER macro=copy_to_state
		state.BgpConfig.KeepaliveTime = types.Int64PointerValue(ans.BgpConfig.KeepaliveTime)
		// property: name=local_as_num, type=STRING macro=copy_to_state
		state.BgpConfig.LocalAsNum = types.StringPointerValue(ans.BgpConfig.LocalAsNum)
		// property: name=md5_secret, type=STRING macro=copy_to_state
		state.BgpConfig.Md5Secret = types.StringPointerValue(plan.BgpConfig.Md5Secret.ValueStringPointer())
		// this property is sensitive and will be stored in the state's internal key name
		state.BgpConfig.Md5SecretInternalKeyName = types.StringValue(GenerateRandomString(16))
		// store value if needed
		if !state.BgpConfig.Md5Secret.IsNull() {
			encryptedMd5Secret, _ := Encrypt([]byte(state.BgpConfig.Md5Secret.String()))
			resp.Private.SetKey(ctx, state.BgpConfig.Md5SecretInternalKeyName.String(), []byte(encryptedMd5Secret))
		}
		// property: name=multi_hop_limit, type=INTEGER macro=copy_to_state
		state.BgpConfig.MultiHopLimit = types.Int64PointerValue(ans.BgpConfig.MultiHopLimit)
		// property: name=peer_auth_type, type=STRING macro=copy_to_state
		state.BgpConfig.PeerAuthType = types.StringPointerValue(ans.BgpConfig.PeerAuthType)
		// property: name=peer_retry_time, type=INTEGER macro=copy_to_state
		state.BgpConfig.PeerRetryTime = types.Int64PointerValue(ans.BgpConfig.PeerRetryTime)
	}
	// property: name=description, type=STRING macro=copy_to_state
	state.Description = types.StringPointerValue(ans.Description)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=name, type=STRING macro=copy_to_state
	state.Name = types.StringPointerValue(ans.Name)
	// property: name=peer_ip, type=STRING macro=copy_to_state
	state.PeerIp = types.StringPointerValue(ans.PeerIp)
	// property: name=peer_ip_v6, type=STRING macro=copy_to_state
	state.PeerIpV6 = types.StringPointerValue(ans.PeerIpV6)
	// property: name=peer_type, type=STRING macro=copy_to_state
	state.PeerType = types.StringPointerValue(ans.PeerType)
	// property: name=remote_as_num, type=STRING macro=copy_to_state
	state.RemoteAsNum = types.StringPointerValue(ans.RemoteAsNum)
	// property: name=route_aggregation, type=REFERENCE macro=copy_to_state
	if ans.RouteAggregation == nil {
		state.RouteAggregation = nil
	} else {
		state.RouteAggregation = &rsModelRouteAggregation{}
		// copy_to_state: state=state.RouteAggregation prefix=rsModel ans=ans.RouteAggregation properties=4
		tflog.Debug(ctx, "copy_to_state state=state.RouteAggregation prefix=rsModel ans=ans.RouteAggregation")
		// property: name=aggregate_prefixes, type=ARRAY_REFERENCE macro=copy_to_state
		if ans.RouteAggregation.AggregatePrefixes == nil {
			state.RouteAggregation.AggregatePrefixes = nil
		} else if len(ans.RouteAggregation.AggregatePrefixes) == 0 {
			state.RouteAggregation.AggregatePrefixes = []rsModelAggregatePrefixes{}
		} else {
			state.RouteAggregation.AggregatePrefixes = make([]rsModelAggregatePrefixes, 0, len(ans.RouteAggregation.AggregatePrefixes))
			for varLoopAggregatePrefixesIndex, varLoopAggregatePrefixes := range ans.RouteAggregation.AggregatePrefixes {
				// add a new item
				state.RouteAggregation.AggregatePrefixes = append(state.RouteAggregation.AggregatePrefixes, rsModelAggregatePrefixes{})
				// copy_to_state: state=state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex] prefix=rsModel ans=varLoopAggregatePrefixes properties=2
				tflog.Debug(ctx, "copy_to_state state=state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex] prefix=rsModel ans=varLoopAggregatePrefixes")
				// property: name=ip_prefixes, type=ARRAY_PRIMITIVE macro=copy_to_state
				varIpPrefixes, errIpPrefixes := types.ListValueFrom(ctx, types.StringType, varLoopAggregatePrefixes.IpPrefixes)
				state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex].IpPrefixes = varIpPrefixes
				resp.Diagnostics.Append(errIpPrefixes.Errors()...)
				// property: name=type, type=STRING macro=copy_to_state
				state.RouteAggregation.AggregatePrefixes[varLoopAggregatePrefixesIndex].Type = types.StringPointerValue(varLoopAggregatePrefixes.Type)
			}
		}
		// property: name=aggregate_type, type=STRING macro=copy_to_state
		state.RouteAggregation.AggregateType = types.StringPointerValue(ans.RouteAggregation.AggregateType)
		// property: name=ipv4_prefix_list_id, type=STRING macro=copy_to_state
		state.RouteAggregation.Ipv4PrefixListId = types.StringPointerValue(ans.RouteAggregation.Ipv4PrefixListId)
		// property: name=ipv6_prefix_list_id, type=STRING macro=copy_to_state
		state.RouteAggregation.Ipv6PrefixListId = types.StringPointerValue(ans.RouteAggregation.Ipv6PrefixListId)
	}
	// property: name=route_map_in_id, type=STRING macro=copy_to_state
	state.RouteMapInId = types.StringPointerValue(ans.RouteMapInId)
	// property: name=route_map_out_id, type=STRING macro=copy_to_state
	state.RouteMapOutId = types.StringPointerValue(ans.RouteMapOutId)
	// property: name=router_id, type=STRING macro=copy_to_state
	state.RouterId = types.StringPointerValue(ans.RouterId)
	// property: name=scope, type=STRING macro=copy_to_state
	state.Scope = types.StringPointerValue(ans.Scope)
	// property: name=shutdown, type=BOOLEAN macro=copy_to_state
	state.Shutdown = types.BoolPointerValue(ans.Shutdown)
	// property: name=tags, type=SET_PRIMITIVE macro=copy_to_state
	varTags, errTags := types.SetValueFrom(ctx, types.StringType, ans.Tags)
	state.Tags = varTags
	resp.Diagnostics.Append(errTags.Errors()...)
	// property: name=update_source, type=STRING macro=copy_to_state
	state.UpdateSource = types.StringPointerValue(ans.UpdateSource)
	// property: name=update_source_v6, type=STRING macro=copy_to_state
	state.UpdateSourceV6 = types.StringPointerValue(ans.UpdateSourceV6)
	// property: name=vrf_context_id, type=STRING macro=copy_to_state
	state.VrfContextId = types.StringPointerValue(ans.VrfContextId)
	return true
}

func (r *elementBgpPeerResource) doDelete(ctx context.Context, state *rsModelBGPPeerConfigScreenV2N6, resp *resource.DeleteResponse) bool {
	// read object id
	tfid := state.Tfid.ValueString()
	// Basic logging.
	tflog.Info(ctx, "performing resource delete", map[string]any{
		"terraform_provider_function": "Delete",
		"resource_name":               "prismasdwan_element_bgp_peer",
		"locMap":                      map[string]int{"prefix_id": 0},
	})

	// tokens must match
	tokens := strings.Split(tfid, IdSeparator)
	if len(tokens) < 3 {
		resp.Diagnostics.AddError("error in prismasdwan_element_bgp_peer ID format", "Expected 3 tokens")
		return false
	}

	// Prepare input for the API endpoint.
	delete_request := &sdwan_client.SdwanClientRequestResponse{}
	delete_request.ResourceType = "prismasdwan_element_bgp_peer"
	delete_request.Method = "DELETE"
	delete_request.Path = "/sdwan/v2.6/api/sites/{site_id}/elements/{element_id}/bgppeers/{bgp_peer_id}"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, state.TfParameters)
	delete_request.PathParameters = &params
	// add last parameter as ObjectID
	(*delete_request.PathParameters)["bgp_peer_id"] = &tokens[0]
	// add other parameters by splitting on `=`
	for _, token := range tokens[1:] {
		param := strings.Split(token, "=")
		(*delete_request.PathParameters)[param[0]] = &param[1]
	}

	// Client that will perform the request.
	svc := sdwan_client.NewClient(r.client)

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, delete_request)
	if delete_request.ResponseErr != nil {
		if !IsObjectNotFound(*delete_request.ResponseErr) {
			resp.Diagnostics.AddError("error deleting prismasdwan_element_bgp_peer", (*delete_request.ResponseErr).Error())
			return false
		}
	}
	return true
}

// Performs the Create(POST) Operation on the Resource
// TfID is pulled from plan to use in the creation request
// Path Parameters are encoded into TfID itself
func (r *elementBgpPeerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Info(ctx, "executing resource create for prismasdwan_element_bgp_peer")
	var plan rsModelBGPPeerConfigScreenV2N6
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make post call
	var state rsModelBGPPeerConfigScreenV2N6
	if r.doPost(ctx, &plan, &state, resp) {
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	}
}

// Performs the Read(GET) Operation on the Resource
// TfID is pulled from state to use in the read request
// Path Parameters are extracted TfID itself
func (r *elementBgpPeerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {

	tflog.Info(ctx, "executing resource read for prismasdwan_element_bgp_peer")
	var savestate, state rsModelBGPPeerConfigScreenV2N6
	resp.Diagnostics.Append(req.State.Get(ctx, &savestate)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make a get call
	if r.doGet(ctx, &state, &savestate, &resp.State, resp) {
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	}
}

// Performs the Update(PUT) Operation on the Resource
// TfID is pulled from state to use in the read request
// Path Parameters are extracted TfID itself
// TfID must match in state and plan, else error is thrown
func (r *elementBgpPeerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {

	tflog.Info(ctx, "executing resource update for prismasdwan_element_bgp_peer")
	var plan, state rsModelBGPPeerConfigScreenV2N6
	// copy state from TF
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// copy plan from TF
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make a put call
	if r.doPut(ctx, &plan, &state, &resp.State, resp) {
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	}
}

// Performs the Delete Operation on the Resource
// TfID is pulled from state to use in the deletion request
// Path Parameters are extracted from the TfID itself
func (r *elementBgpPeerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {

	tflog.Info(ctx, "executing resource delete for prismasdwan_element_bgp_peer")
	var state rsModelBGPPeerConfigScreenV2N6
	// copy state from TF
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make a delete call
	if r.doDelete(ctx, &state, resp) {
		resp.State.RemoveResource(ctx)
	}
}

func (r *elementBgpPeerResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("tfid"), req, resp)
}
