package provider

// Note:  This file is automatically generated.  Manually made changes
// will be overwritten when the provider is generated.

import (
	"context"
	"encoding/json"
	"strings"

	sdwan "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk"
	sdwan_schema "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/schemas"
	sdwan_client "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/services"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	rsschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/tidwall/sjson"
)

// +-----------------------------------------------------------------
// | Schema Map Summary (size=goLangStructMap=2)
// | Computed Resource Name=sites_elements_staticroutes
// +-----------------------------------------------------------------
// | NextHop HasID=false
// | StaticRouteV2N3 HasID=true
// +-----------------------------------------------------------------

// Resource.
var (
	_ resource.Resource                = &elementStaticRouteResource{}
	_ resource.ResourceWithConfigure   = &elementStaticRouteResource{}
	_ resource.ResourceWithImportState = &elementStaticRouteResource{}
)

// To enable this data source for TF Provider, go to `provider.go` and inject this into the function
// as below:
//
//	func (p *SdwanProvider) Resources(_ context.Context) []func() resource.Resource {
//	  	return []func() resource.Resource{
//	     ... <other existing resources>
//	     NewElementStaticRouteResource,
//	     // -- append next resource above -- //
//	     }
//	  }
func NewElementStaticRouteResource() resource.Resource {
	return &elementStaticRouteResource{}
}

type elementStaticRouteResource struct {
	client *sdwan.Client
}

// Metadata returns the data source type name.
func (r *elementStaticRouteResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "prismasdwan_element_static_route"
}

// Schema defines the schema for this data source.
func (r *elementStaticRouteResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = rsschema.Schema{
		Description: "Retrieves a config item.",
		Attributes: map[string]rsschema.Attribute{
			"tfid": rsschema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			// rest all properties to be read from GET API Schema schema=StaticRouteV2N3
			// generic x_parameters is added to accomodate path parameters
			"x_parameters": rsschema.MapAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				ElementType: types.StringType,
			},
			// property: name=_etag, type=INTEGER macro=rss_schema
			"x_etag": rsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_etag, type=INTEGER macro=rss_schema
			// property: name=_schema, type=INTEGER macro=rss_schema
			"x_schema": rsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_schema, type=INTEGER macro=rss_schema
			// property: name=address_family, type=STRING macro=rss_schema
			"address_family": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=address_family, type=STRING macro=rss_schema
			// property: name=description, type=STRING macro=rss_schema
			"description": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=description, type=STRING macro=rss_schema
			// property: name=destination_prefix, type=STRING macro=rss_schema
			"destination_prefix": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=destination_prefix, type=STRING macro=rss_schema
			// property: name=id, type=STRING macro=rss_schema
			"id": rsschema.StringAttribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=id, type=STRING macro=rss_schema
			// property: name=name, type=STRING macro=rss_schema
			"name": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=name, type=STRING macro=rss_schema
			// property: name=network_context_id, type=STRING macro=rss_schema
			"network_context_id": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=network_context_id, type=STRING macro=rss_schema
			// property: name=nexthop_reachability_probe, type=BOOLEAN macro=rss_schema
			"nexthop_reachability_probe": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=nexthop_reachability_probe, type=BOOLEAN macro=rss_schema
			// property: name=nexthops, type=ARRAY_REFERENCE macro=rss_schema
			"nexthops": rsschema.ListNestedAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
				NestedObject: rsschema.NestedAttributeObject{
					Attributes: map[string]rsschema.Attribute{
						// property: name=admin_distance, type=INTEGER macro=rss_schema
						"admin_distance": rsschema.Int64Attribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=admin_distance, type=INTEGER macro=rss_schema
						// property: name=nexthop_interface_id, type=STRING macro=rss_schema
						"nexthop_interface_id": rsschema.StringAttribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=nexthop_interface_id, type=STRING macro=rss_schema
						// property: name=nexthop_ip, type=STRING macro=rss_schema
						"nexthop_ip": rsschema.StringAttribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=nexthop_ip, type=STRING macro=rss_schema
						// property: name=self, type=BOOLEAN macro=rss_schema
						"self": rsschema.BoolAttribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=self, type=BOOLEAN macro=rss_schema
					},
				},
			},
			// key name holder for attribute: name=self, type=BOOLEAN macro=rss_schema
			// property: name=scope, type=STRING macro=rss_schema
			"scope": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=scope, type=STRING macro=rss_schema
			// property: name=tags, type=SET_PRIMITIVE macro=rss_schema
			"tags": rsschema.SetAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ElementType: types.StringType,
			},
			// key name holder for attribute: name=tags, type=SET_PRIMITIVE macro=rss_schema
			// property: name=vrf_context_id, type=STRING macro=rss_schema
			"vrf_context_id": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=vrf_context_id, type=STRING macro=rss_schema
		},
	}
}

// Configure prepares the struct.
func (r *elementStaticRouteResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*sdwan.Client)
}

// in some apis the status code is not consistent and hence we may have to act upon
// specific error codes instead
func (r *elementStaticRouteResource) GetHttpStatusCode(request *sdwan_client.SdwanClientRequestResponse) int {
	if request.ResponseErrorCode == nil {
		return request.ResponseStatusCode
	}
	switch *request.ResponseErrorCode {
	case "OBJECT_NOT_FOUND":
		return 404
	default:
		return request.ResponseStatusCode
	}
}

func (r *elementStaticRouteResource) doPost(ctx context.Context, plan *rsModelStaticRouteV2N3, state *rsModelStaticRouteV2N3, resp *resource.CreateResponse) bool {
	tflog.Info(ctx, "executing http post for prismasdwan_element_static_route")
	// Basic logging.
	tflog.Info(ctx, "performing resource create", map[string]any{
		"resource_name":               "prismasdwan_element_static_route",
		"terraform_provider_function": "Create",
	})

	// Prepare input for the API endpoint.
	create_request := &sdwan_client.SdwanClientRequestResponse{}
	create_request.ResourceType = "prismasdwan_element_static_route"
	create_request.Method = "POST"
	create_request.Path = "/sdwan/v2.3/api/sites/{site_id}/elements/{element_id}/staticroutes"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, plan.TfParameters)
	create_request.PathParameters = &params

	// Client that will perform the request.
	svc := sdwan_client.NewClient(r.client)

	// prepare request from state
	var body = &sdwan_schema.StaticRouteV2N3{}

	// copy from plan to body
	// copy_from_plan: body=body prefix=rsModel plan=plan properties=13
	// property: name=_etag, type=INTEGER macro=copy_from_plan
	body.Etag = Int64ValueOrNil(plan.Etag)
	// property: name=_schema, type=INTEGER macro=copy_from_plan
	body.Schema = Int64ValueOrNil(plan.Schema)
	// property: name=address_family, type=STRING macro=copy_from_plan
	body.AddressFamily = StringValueOrNil(plan.AddressFamily)
	// property: name=description, type=STRING macro=copy_from_plan
	body.Description = StringValueOrNil(plan.Description)
	// property: name=destination_prefix, type=STRING macro=copy_from_plan
	body.DestinationPrefix = StringValueOrNil(plan.DestinationPrefix)
	// property: name=id, type=STRING macro=copy_from_plan
	body.Id = StringValueOrNil(plan.Id)
	// property: name=name, type=STRING macro=copy_from_plan
	body.Name = StringValueOrNil(plan.Name)
	// property: name=network_context_id, type=STRING macro=copy_from_plan
	body.NetworkContextId = StringValueOrNil(plan.NetworkContextId)
	// property: name=nexthop_reachability_probe, type=BOOLEAN macro=copy_from_plan
	body.NexthopReachabilityProbe = BoolValueOrNil(plan.NexthopReachabilityProbe)
	// property: name=nexthops, type=ARRAY_REFERENCE macro=copy_from_plan
	if plan.Nexthops == nil {
		body.Nexthops = nil
	} else if len(plan.Nexthops) == 0 {
		body.Nexthops = []sdwan_schema.NextHop{}
	} else {
		body.Nexthops = make([]sdwan_schema.NextHop, 0, len(plan.Nexthops))
		for varLoopNexthopsIndex, varLoopNexthops := range plan.Nexthops {
			// add a new item
			body.Nexthops = append(body.Nexthops, sdwan_schema.NextHop{})
			// copy_from_plan: body=body.Nexthops[varLoopNexthopsIndex] prefix=rsModel plan=varLoopNexthops properties=4
			// property: name=admin_distance, type=INTEGER macro=copy_from_plan
			body.Nexthops[varLoopNexthopsIndex].AdminDistance = Int64ValueOrNil(varLoopNexthops.AdminDistance)
			// property: name=nexthop_interface_id, type=STRING macro=copy_from_plan
			body.Nexthops[varLoopNexthopsIndex].NexthopInterfaceId = StringValueOrNil(varLoopNexthops.NexthopInterfaceId)
			// property: name=nexthop_ip, type=STRING macro=copy_from_plan
			body.Nexthops[varLoopNexthopsIndex].NexthopIp = StringValueOrNil(varLoopNexthops.NexthopIp)
			// property: name=self, type=BOOLEAN macro=copy_from_plan
			body.Nexthops[varLoopNexthopsIndex].Self = BoolValueOrNil(varLoopNexthops.Self)
		}
	}
	// property: name=scope, type=STRING macro=copy_from_plan
	body.Scope = StringValueOrNil(plan.Scope)
	// property: name=tags, type=SET_PRIMITIVE macro=copy_from_plan
	body.Tags = SetStringValueOrNil(ctx, plan.Tags)
	// property: name=vrf_context_id, type=STRING macro=copy_from_plan
	body.VrfContextId = StringValueOrNil(plan.VrfContextId)

	// convert body to map
	json_body, err := json.Marshal(body)
	if err != nil {
		resp.Diagnostics.AddError("error marshaling struct StaticRouteV2N3 to JSON:", err.Error())
		return false
	}

	// process http json path
	request_body_string := string(json_body)
	// inject overrides
	request_body_string, _ = sjson.Delete(request_body_string, "id")
	request_body_string, _ = sjson.Delete(request_body_string, "_etag")
	request_body_string, _ = sjson.Set(request_body_string, "_schema", 0)
	// copy pointer
	create_request.RequestBody = &request_body_string

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, create_request)
	if create_request.ResponseErr != nil {
		tflog.Info(ctx, "create request failed for prismasdwan_element_static_route", map[string]any{
			"terraform_provider_function": "Create",
			"resource_name":               "prismasdwan_element_static_route",
			"path":                        create_request.FinalPath,
		})
		tflog.Debug(ctx, "create request failed for prismasdwan_element_static_route", map[string]any{
			"terraform_provider_function": "Create",
			"resource_name":               "prismasdwan_element_static_route",
			"path":                        create_request.FinalPath,
			"request":                     create_request.ToString(),
		})
		resp.Diagnostics.AddError("error creating prismasdwan_element_static_route", (*create_request.ResponseErr).Error())
		return false
	}

	// process http json path
	response_body_string := string(*create_request.ResponseBytes)
	// inject overrides
	response_body_string, _ = sjson.Delete(response_body_string, "_created_on_utc")
	response_body_string, _ = sjson.Set(response_body_string, "_schema", 0)

	// start copying attributes
	var ans sdwan_schema.StaticRouteV2N3
	// copy from json response
	json_err := json.Unmarshal([]byte(response_body_string), &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to StaticRouteV2N3 in create", json_err.Error())
		return false
	}

	// Create the Terraform ID.
	var idBuilder strings.Builder
	if ans.Id == nil {
		resp.Diagnostics.AddError("Undefined param required for ID", "Id")
		return false
	}
	// ID Format: Id:Param1=Value1:Param2=Value2:...:ParamN=ValueN
	if ans.Id != nil {
		idBuilder.WriteString(*ans.Id)
		for p, v := range *create_request.PathParameters {
			idBuilder.WriteString(IdSeparator)
			idBuilder.WriteString(p)
			idBuilder.WriteString("=")
			idBuilder.WriteString(*v)
		}
	}
	// set the tf id for the resource created
	state.Tfid = types.StringValue(idBuilder.String())
	state.TfParameters = plan.TfParameters
	tflog.Info(ctx, "created prismasdwan_element_static_route with ID", map[string]any{"tfid": state.Tfid.ValueString()})

	// Store the answer to state. schema=StaticRouteV2N3
	// copy_to_state: state=state prefix=rsModel ans=ans properties=13
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=address_family, type=STRING macro=copy_to_state
	state.AddressFamily = types.StringPointerValue(ans.AddressFamily)
	// property: name=description, type=STRING macro=copy_to_state
	state.Description = types.StringPointerValue(ans.Description)
	// property: name=destination_prefix, type=STRING macro=copy_to_state
	state.DestinationPrefix = types.StringPointerValue(ans.DestinationPrefix)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=name, type=STRING macro=copy_to_state
	state.Name = types.StringPointerValue(ans.Name)
	// property: name=network_context_id, type=STRING macro=copy_to_state
	state.NetworkContextId = types.StringPointerValue(ans.NetworkContextId)
	// property: name=nexthop_reachability_probe, type=BOOLEAN macro=copy_to_state
	state.NexthopReachabilityProbe = types.BoolPointerValue(ans.NexthopReachabilityProbe)
	// property: name=nexthops, type=ARRAY_REFERENCE macro=copy_to_state
	if ans.Nexthops == nil {
		state.Nexthops = nil
	} else if len(ans.Nexthops) == 0 {
		state.Nexthops = []rsModelNextHop{}
	} else {
		state.Nexthops = make([]rsModelNextHop, 0, len(ans.Nexthops))
		for varLoopNexthopsIndex, varLoopNexthops := range ans.Nexthops {
			// add a new item
			state.Nexthops = append(state.Nexthops, rsModelNextHop{})
			// copy_to_state: state=state.Nexthops[varLoopNexthopsIndex] prefix=rsModel ans=varLoopNexthops properties=4
			// property: name=admin_distance, type=INTEGER macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].AdminDistance = types.Int64PointerValue(varLoopNexthops.AdminDistance)
			// property: name=nexthop_interface_id, type=STRING macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].NexthopInterfaceId = types.StringPointerValue(varLoopNexthops.NexthopInterfaceId)
			// property: name=nexthop_ip, type=STRING macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].NexthopIp = types.StringPointerValue(varLoopNexthops.NexthopIp)
			// property: name=self, type=BOOLEAN macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].Self = types.BoolPointerValue(varLoopNexthops.Self)
		}
	}
	// property: name=scope, type=STRING macro=copy_to_state
	state.Scope = types.StringPointerValue(ans.Scope)
	// property: name=tags, type=SET_PRIMITIVE macro=copy_to_state
	varTags, errTags := types.SetValueFrom(ctx, types.StringType, ans.Tags)
	state.Tags = varTags
	resp.Diagnostics.Append(errTags.Errors()...)
	// property: name=vrf_context_id, type=STRING macro=copy_to_state
	state.VrfContextId = types.StringPointerValue(ans.VrfContextId)
	return true
}

func (r *elementStaticRouteResource) doGet(ctx context.Context, state *rsModelStaticRouteV2N3, savestate *rsModelStaticRouteV2N3, State *tfsdk.State, resp *resource.ReadResponse) bool {
	// Basic logging.
	tfid := savestate.Tfid.ValueString()
	tflog.Info(ctx, "performing resource read", map[string]any{
		"terraform_provider_function": "Read",
		"resource_name":               "prismasdwan_element_static_route",
		"tfid":                        tfid,
	})

	tokens := strings.Split(tfid, IdSeparator)
	if len(tokens) != 3 {
		resp.Diagnostics.AddError("error in prismasdwan_element_static_route ID format", "Expected 3 tokens")
		return false
	}

	// Prepare to read the config.
	svc := sdwan_client.NewClient(r.client)

	// Prepare input for the API endpoint.
	read_request := &sdwan_client.SdwanClientRequestResponse{}
	read_request.ResourceType = "prismasdwan_element_static_route"
	read_request.Method = "GET"
	read_request.Path = "/sdwan/v2.3/api/sites/{site_id}/elements/{element_id}/staticroutes/{static_route_id}"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, savestate.TfParameters)
	read_request.PathParameters = &params
	// add last parameter as ObjectID
	(*read_request.PathParameters)["static_route_id"] = &tokens[0]
	// add other parameters by splitting on `=`
	for _, token := range tokens[1:] {
		param := strings.Split(token, "=")
		(*read_request.PathParameters)[param[0]] = &param[1]
	}

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, read_request)
	if read_request.ResponseErr != nil {
		if IsObjectNotFound(*read_request.ResponseErr) {
			State.RemoveResource(ctx)
		} else if r.GetHttpStatusCode(read_request) == 404 {
			State.RemoveResource(ctx)
		} else {
			tflog.Info(ctx, "read request failed for prismasdwan_element_static_route", map[string]any{
				"terraform_provider_function": "Read",
				"resource_name":               "prismasdwan_element_static_route",
				"path":                        read_request.FinalPath,
				"request":                     read_request.ToString(),
			})
			resp.Diagnostics.AddError("error reading prismasdwan_element_static_route from sdwan servers", (*read_request.ResponseErr).Error())
		}
		return false
	}

	// process http json path
	response_body_string := string(*read_request.ResponseBytes)
	// inject overrides
	response_body_string, _ = sjson.Delete(response_body_string, "_created_on_utc")
	response_body_string, _ = sjson.Set(response_body_string, "_schema", 0)

	// Store the answer to state. schema=StaticRouteV2N3
	state.Tfid = savestate.Tfid
	// copy parameters from savestate as they are
	if savestate.TfParameters.IsNull() {
		state.TfParameters = types.MapNull(types.StringType)
	} else {
		state.TfParameters = savestate.TfParameters
	}
	// start copying attributes
	var ans sdwan_schema.StaticRouteV2N3
	// copy from json response
	json_err := json.Unmarshal([]byte(response_body_string), &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to StaticRouteV2N3 in read", json_err.Error())
		return false
	}
	// lets copy all items into state
	// copy_to_state: state=state prefix=rsModel ans=ans properties=13
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=address_family, type=STRING macro=copy_to_state
	state.AddressFamily = types.StringPointerValue(ans.AddressFamily)
	// property: name=description, type=STRING macro=copy_to_state
	state.Description = types.StringPointerValue(ans.Description)
	// property: name=destination_prefix, type=STRING macro=copy_to_state
	state.DestinationPrefix = types.StringPointerValue(ans.DestinationPrefix)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=name, type=STRING macro=copy_to_state
	state.Name = types.StringPointerValue(ans.Name)
	// property: name=network_context_id, type=STRING macro=copy_to_state
	state.NetworkContextId = types.StringPointerValue(ans.NetworkContextId)
	// property: name=nexthop_reachability_probe, type=BOOLEAN macro=copy_to_state
	state.NexthopReachabilityProbe = types.BoolPointerValue(ans.NexthopReachabilityProbe)
	// property: name=nexthops, type=ARRAY_REFERENCE macro=copy_to_state
	if ans.Nexthops == nil {
		state.Nexthops = nil
	} else if len(ans.Nexthops) == 0 {
		state.Nexthops = []rsModelNextHop{}
	} else {
		state.Nexthops = make([]rsModelNextHop, 0, len(ans.Nexthops))
		for varLoopNexthopsIndex, varLoopNexthops := range ans.Nexthops {
			// add a new item
			state.Nexthops = append(state.Nexthops, rsModelNextHop{})
			// copy_to_state: state=state.Nexthops[varLoopNexthopsIndex] prefix=rsModel ans=varLoopNexthops properties=4
			// property: name=admin_distance, type=INTEGER macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].AdminDistance = types.Int64PointerValue(varLoopNexthops.AdminDistance)
			// property: name=nexthop_interface_id, type=STRING macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].NexthopInterfaceId = types.StringPointerValue(varLoopNexthops.NexthopInterfaceId)
			// property: name=nexthop_ip, type=STRING macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].NexthopIp = types.StringPointerValue(varLoopNexthops.NexthopIp)
			// property: name=self, type=BOOLEAN macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].Self = types.BoolPointerValue(varLoopNexthops.Self)
		}
	}
	// property: name=scope, type=STRING macro=copy_to_state
	state.Scope = types.StringPointerValue(ans.Scope)
	// property: name=tags, type=SET_PRIMITIVE macro=copy_to_state
	varTags, errTags := types.SetValueFrom(ctx, types.StringType, ans.Tags)
	state.Tags = varTags
	resp.Diagnostics.Append(errTags.Errors()...)
	// property: name=vrf_context_id, type=STRING macro=copy_to_state
	state.VrfContextId = types.StringPointerValue(ans.VrfContextId)
	return true
}

func (r *elementStaticRouteResource) doPut(ctx context.Context, plan *rsModelStaticRouteV2N3, state *rsModelStaticRouteV2N3, State *tfsdk.State, resp *resource.UpdateResponse) bool {
	state_tfid := state.Tfid.ValueString()
	plan_tfid := plan.Tfid.ValueString()
	// Basic logging.
	tflog.Info(ctx, "performing resource update", map[string]any{
		"terraform_provider_function": "Update",
		"resource_name":               "prismasdwan_element_static_route",
		"state_tfid":                  state_tfid,
		"plan_tfid":                   plan_tfid,
	})

	// both TFID must be SAME!!!
	if state_tfid != plan_tfid {
		resp.Diagnostics.AddError("error updating prismasdwan_element_static_route", "state and plan TFID do not match")
		return false
	}

	// split tokens
	tokens := strings.Split(state_tfid, IdSeparator)
	if len(tokens) != 3 {
		resp.Diagnostics.AddError("error in prismasdwan_element_static_route ID format", "Expected 3 tokens")
		return false
	}

	// Prepare input for the API endpoint.
	put_request := &sdwan_client.SdwanClientRequestResponse{}
	put_request.ResourceType = "prismasdwan_element_static_route"
	put_request.Method = "PUT"
	put_request.Path = "/sdwan/v2.3/api/sites/{site_id}/elements/{element_id}/staticroutes/{static_route_id}"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, state.TfParameters)
	put_request.PathParameters = &params
	// add last parameter as ObjectID
	(*put_request.PathParameters)["static_route_id"] = &tokens[0]
	// add other parameters by splitting on `=`
	for _, token := range tokens[1:] {
		param := strings.Split(token, "=")
		(*put_request.PathParameters)[param[0]] = &param[1]
	}

	// Client that will perform the request.
	svc := sdwan_client.NewClient(r.client)

	// prepare request from state
	var body = &sdwan_schema.StaticRouteV2N3{}

	// now we create the JSON request from the state/plan created by TF
	// below copy code generated from macro copy_from_plan_or_state
	// copy_from_plan_or_state: body=body prefix=rsModel state=state plan=plan properties=13
	// property: name=_etag, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.Etag = ValueInt64PointerFromPlanOrState(plan.Etag, state.Etag)
	} else {
		body.Etag = Int64ValueOrNil(plan.Etag)
	}
	// property: name=_schema, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.Schema = ValueInt64PointerFromPlanOrState(plan.Schema, state.Schema)
	} else {
		body.Schema = Int64ValueOrNil(plan.Schema)
	}
	// property: name=address_family, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.AddressFamily = ValueStringPointerFromPlanOrState(plan.AddressFamily, state.AddressFamily)
	} else {
		body.AddressFamily = StringValueOrNil(plan.AddressFamily)
	}
	// property: name=description, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Description = ValueStringPointerFromPlanOrState(plan.Description, state.Description)
	} else {
		body.Description = StringValueOrNil(plan.Description)
	}
	// property: name=destination_prefix, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.DestinationPrefix = ValueStringPointerFromPlanOrState(plan.DestinationPrefix, state.DestinationPrefix)
	} else {
		body.DestinationPrefix = StringValueOrNil(plan.DestinationPrefix)
	}
	// property: name=id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Id = ValueStringPointerFromPlanOrState(plan.Id, state.Id)
	} else {
		body.Id = StringValueOrNil(plan.Id)
	}
	// property: name=name, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Name = ValueStringPointerFromPlanOrState(plan.Name, state.Name)
	} else {
		body.Name = StringValueOrNil(plan.Name)
	}
	// property: name=network_context_id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.NetworkContextId = ValueStringPointerFromPlanOrState(plan.NetworkContextId, state.NetworkContextId)
	} else {
		body.NetworkContextId = StringValueOrNil(plan.NetworkContextId)
	}
	// property: name=nexthop_reachability_probe, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.NexthopReachabilityProbe = ValueBoolPointerFromPlanOrState(plan.NexthopReachabilityProbe, state.NexthopReachabilityProbe)
	} else {
		body.NexthopReachabilityProbe = BoolValueOrNil(plan.NexthopReachabilityProbe)
	}
	// property: name=nexthops, type=ARRAY_REFERENCE macro=copy_from_plan_or_state
	if plan.Nexthops == nil && (state == nil || state.Nexthops == nil) {
		body.Nexthops = nil
	} else if len(plan.Nexthops) == 0 && (state == nil || len(state.Nexthops) == 0) {
		body.Nexthops = []sdwan_schema.NextHop{}
	} else if len(plan.Nexthops) != 0 || (state != nil && len(state.Nexthops) != 0) {
		NexthopsToUse := plan.Nexthops
		if len(plan.Nexthops) == 0 {
			NexthopsToUse = state.Nexthops
		}
		body.Nexthops = make([]sdwan_schema.NextHop, 0, len(NexthopsToUse))
		for varLoopNexthopsIndex, varLoopNexthops := range NexthopsToUse {
			// add a new item
			body.Nexthops = append(body.Nexthops, sdwan_schema.NextHop{})
			// since we have chosen to stick with either the plan or state, we need to simply copy child properties
			// copy_from_plan: body=body.Nexthops[varLoopNexthopsIndex] prefix=rsModel plan=varLoopNexthops properties=4
			// property: name=admin_distance, type=INTEGER macro=copy_from_plan
			body.Nexthops[varLoopNexthopsIndex].AdminDistance = Int64ValueOrNil(varLoopNexthops.AdminDistance)
			// property: name=nexthop_interface_id, type=STRING macro=copy_from_plan
			body.Nexthops[varLoopNexthopsIndex].NexthopInterfaceId = StringValueOrNil(varLoopNexthops.NexthopInterfaceId)
			// property: name=nexthop_ip, type=STRING macro=copy_from_plan
			body.Nexthops[varLoopNexthopsIndex].NexthopIp = StringValueOrNil(varLoopNexthops.NexthopIp)
			// property: name=self, type=BOOLEAN macro=copy_from_plan
			body.Nexthops[varLoopNexthopsIndex].Self = BoolValueOrNil(varLoopNexthops.Self)
		}
	}
	// property: name=scope, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Scope = ValueStringPointerFromPlanOrState(plan.Scope, state.Scope)
	} else {
		body.Scope = StringValueOrNil(plan.Scope)
	}
	// property: name=tags, type=SET_PRIMITIVE macro=copy_from_plan_or_state
	body.Tags = SetStringValueOrNil(ctx, plan.Tags)
	// property: name=vrf_context_id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.VrfContextId = ValueStringPointerFromPlanOrState(plan.VrfContextId, state.VrfContextId)
	} else {
		body.VrfContextId = StringValueOrNil(plan.VrfContextId)
	}

	// convert body to map
	json_body, err := json.Marshal(body)
	if err != nil {
		resp.Diagnostics.AddError("error marshaling struct StaticRouteV2N3 to JSON:", err.Error())
		return false
	}

	// process http json path
	request_body_string := string(json_body)
	// copy pointer
	put_request.RequestBody = &request_body_string

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, put_request)
	if put_request.ResponseErr != nil {
		if IsObjectNotFound(*put_request.ResponseErr) {
			State.RemoveResource(ctx)
		} else if r.GetHttpStatusCode(put_request) == 404 {
			State.RemoveResource(ctx)
		} else {
			tflog.Info(ctx, "update request failed for prismasdwan_element_static_route", map[string]any{
				"terraform_provider_function": "Update",
				"resource_name":               "prismasdwan_element_static_route",
				"path":                        put_request.FinalPath,
			})
			tflog.Debug(ctx, "update request failed for prismasdwan_element_static_route", map[string]any{
				"terraform_provider_function": "Update",
				"resource_name":               "prismasdwan_element_static_route",
				"path":                        put_request.FinalPath,
				"request":                     put_request.ToString(),
			})
			resp.Diagnostics.AddError("error updating prismasdwan_element_static_route", (*put_request.ResponseErr).Error())
		}
		return false
	}

	// process http json path
	response_body_string := string(*put_request.ResponseBytes)
	// inject overrides
	response_body_string, _ = sjson.Delete(response_body_string, "_created_on_utc")
	response_body_string, _ = sjson.Set(response_body_string, "_schema", 0)

	// start copying attributes
	var ans sdwan_schema.StaticRouteV2N3
	// copy from json response
	json_err := json.Unmarshal([]byte(response_body_string), &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to StaticRouteV2N3 in update", json_err.Error())
		return false
	}

	// Store the answer to state. schema=StaticRouteV2N3
	// copy_to_state: state=state prefix=rsModel ans=ans properties=13
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=address_family, type=STRING macro=copy_to_state
	state.AddressFamily = types.StringPointerValue(ans.AddressFamily)
	// property: name=description, type=STRING macro=copy_to_state
	state.Description = types.StringPointerValue(ans.Description)
	// property: name=destination_prefix, type=STRING macro=copy_to_state
	state.DestinationPrefix = types.StringPointerValue(ans.DestinationPrefix)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=name, type=STRING macro=copy_to_state
	state.Name = types.StringPointerValue(ans.Name)
	// property: name=network_context_id, type=STRING macro=copy_to_state
	state.NetworkContextId = types.StringPointerValue(ans.NetworkContextId)
	// property: name=nexthop_reachability_probe, type=BOOLEAN macro=copy_to_state
	state.NexthopReachabilityProbe = types.BoolPointerValue(ans.NexthopReachabilityProbe)
	// property: name=nexthops, type=ARRAY_REFERENCE macro=copy_to_state
	if ans.Nexthops == nil {
		state.Nexthops = nil
	} else if len(ans.Nexthops) == 0 {
		state.Nexthops = []rsModelNextHop{}
	} else {
		state.Nexthops = make([]rsModelNextHop, 0, len(ans.Nexthops))
		for varLoopNexthopsIndex, varLoopNexthops := range ans.Nexthops {
			// add a new item
			state.Nexthops = append(state.Nexthops, rsModelNextHop{})
			// copy_to_state: state=state.Nexthops[varLoopNexthopsIndex] prefix=rsModel ans=varLoopNexthops properties=4
			// property: name=admin_distance, type=INTEGER macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].AdminDistance = types.Int64PointerValue(varLoopNexthops.AdminDistance)
			// property: name=nexthop_interface_id, type=STRING macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].NexthopInterfaceId = types.StringPointerValue(varLoopNexthops.NexthopInterfaceId)
			// property: name=nexthop_ip, type=STRING macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].NexthopIp = types.StringPointerValue(varLoopNexthops.NexthopIp)
			// property: name=self, type=BOOLEAN macro=copy_to_state
			state.Nexthops[varLoopNexthopsIndex].Self = types.BoolPointerValue(varLoopNexthops.Self)
		}
	}
	// property: name=scope, type=STRING macro=copy_to_state
	state.Scope = types.StringPointerValue(ans.Scope)
	// property: name=tags, type=SET_PRIMITIVE macro=copy_to_state
	varTags, errTags := types.SetValueFrom(ctx, types.StringType, ans.Tags)
	state.Tags = varTags
	resp.Diagnostics.Append(errTags.Errors()...)
	// property: name=vrf_context_id, type=STRING macro=copy_to_state
	state.VrfContextId = types.StringPointerValue(ans.VrfContextId)
	return true
}

func (r *elementStaticRouteResource) doDelete(ctx context.Context, state *rsModelStaticRouteV2N3, resp *resource.DeleteResponse) bool {
	// read object id
	tfid := state.Tfid.ValueString()
	// Basic logging.
	tflog.Info(ctx, "performing resource delete", map[string]any{
		"terraform_provider_function": "Delete",
		"resource_name":               "prismasdwan_element_static_route",
		"locMap":                      map[string]int{"prefix_id": 0},
	})

	// tokens must match
	tokens := strings.Split(tfid, IdSeparator)
	if len(tokens) != 3 {
		resp.Diagnostics.AddError("error in prismasdwan_element_static_route ID format", "Expected 3 tokens")
		return false
	}

	// Prepare input for the API endpoint.
	delete_request := &sdwan_client.SdwanClientRequestResponse{}
	delete_request.ResourceType = "prismasdwan_element_static_route"
	delete_request.Method = "DELETE"
	delete_request.Path = "/sdwan/v2.3/api/sites/{site_id}/elements/{element_id}/staticroutes/{static_route_id}"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, state.TfParameters)
	delete_request.PathParameters = &params
	// add last parameter as ObjectID
	(*delete_request.PathParameters)["static_route_id"] = &tokens[0]
	// add other parameters by splitting on `=`
	for _, token := range tokens[1:] {
		param := strings.Split(token, "=")
		(*delete_request.PathParameters)[param[0]] = &param[1]
	}

	// Client that will perform the request.
	svc := sdwan_client.NewClient(r.client)

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, delete_request)
	if delete_request.ResponseErr != nil {
		if !IsObjectNotFound(*delete_request.ResponseErr) {
			resp.Diagnostics.AddError("error deleting prismasdwan_element_static_route", (*delete_request.ResponseErr).Error())
			return false
		}
	}
	return true
}

// Performs the Create(POST) Operation on the Resource
// TfID is pulled from plan to use in the creation request
// Path Parameters are encoded into TfID itself
func (r *elementStaticRouteResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Info(ctx, "executing resource create for prismasdwan_element_static_route")
	var plan rsModelStaticRouteV2N3
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make post call
	var state rsModelStaticRouteV2N3
	if r.doPost(ctx, &plan, &state, resp) {
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	}
}

// Performs the Read(GET) Operation on the Resource
// TfID is pulled from state to use in the read request
// Path Parameters are extracted TfID itself
func (r *elementStaticRouteResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {

	tflog.Info(ctx, "executing resource read for prismasdwan_element_static_route")
	var savestate, state rsModelStaticRouteV2N3
	resp.Diagnostics.Append(req.State.Get(ctx, &savestate)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make a get call
	if r.doGet(ctx, &state, &savestate, &resp.State, resp) {
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	}
}

// Performs the Update(PUT) Operation on the Resource
// TfID is pulled from state to use in the read request
// Path Parameters are extracted TfID itself
// TfID must match in state and plan, else error is thrown
func (r *elementStaticRouteResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {

	tflog.Info(ctx, "executing resource update for prismasdwan_element_static_route")
	var plan, state rsModelStaticRouteV2N3
	// copy state from TF
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// copy plan from TF
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make a put call
	if r.doPut(ctx, &plan, &state, &resp.State, resp) {
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	}
}

// Performs the Delete Operation on the Resource
// TfID is pulled from state to use in the deletion request
// Path Parameters are extracted from the TfID itself
func (r *elementStaticRouteResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {

	tflog.Info(ctx, "executing resource delete for prismasdwan_element_static_route")
	var state rsModelStaticRouteV2N3
	// copy state from TF
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make a delete call
	if r.doDelete(ctx, &state, resp) {
		resp.State.RemoveResource(ctx)
	}
}

func (r *elementStaticRouteResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("tfid"), req, resp)
}
