package provider

// Note:  This file is automatically generated.  Manually made changes
// will be overwritten when the provider is generated.

import (
	"context"
	"encoding/json"
	"strings"

	sdwan "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk"
	sdwan_schema "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/schemas"
	sdwan_client "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/services"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	rsschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/tidwall/sjson"
)

// +-----------------------------------------------------------------
// | Schema Map Summary (size=goLangStructMap=2)
// | Computed Resource Name=sites_elements_bgpconfigs
// +-----------------------------------------------------------------
// | OspfRedistribution HasID=false
// | BGPGlobalConfigScreenV2N4 HasID=true
// +-----------------------------------------------------------------

// Resource.
var (
	_ resource.Resource                = &sitesElementsBgpconfigsResource{}
	_ resource.ResourceWithConfigure   = &sitesElementsBgpconfigsResource{}
	_ resource.ResourceWithImportState = &sitesElementsBgpconfigsResource{}
)

// To enable this data source for TF Provider, go to `provider.go` and inject this into the function
// as below:
//
//	func (p *SdwanProvider) Resources(_ context.Context) []func() resource.Resource {
//	  	return []func() resource.Resource{
//	     ... <other existing resources>
//	     NewSitesElementsBgpconfigsResource,
//	     // -- append next resource above -- //
//	     }
//	  }
func NewSitesElementsBgpconfigsResource() resource.Resource {
	return &sitesElementsBgpconfigsResource{}
}

type sitesElementsBgpconfigsResource struct {
	client *sdwan.Client
}

// Metadata returns the data source type name.
func (r *sitesElementsBgpconfigsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "prismasdwan_sites_elements_bgpconfigs"
}

// Schema defines the schema for this data source.
func (r *sitesElementsBgpconfigsResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = rsschema.Schema{
		Description: "Retrieves a config item.",
		Attributes: map[string]rsschema.Attribute{
			"tfid": rsschema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			// rest all properties to be read from GET API Schema schema=BGPGlobalConfigScreenV2N4
			// generic x_parameters is added to accomodate path parameters
			"x_parameters": rsschema.MapAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				ElementType: types.StringType,
			},
			// property: name=_etag, type=INTEGER macro=rss_schema
			"x_etag": rsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_etag, type=INTEGER macro=rss_schema
			// property: name=_schema, type=INTEGER macro=rss_schema
			"x_schema": rsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_schema, type=INTEGER macro=rss_schema
			// property: name=admin_distance, type=INTEGER macro=rss_schema
			"admin_distance": rsschema.Int64Attribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=admin_distance, type=INTEGER macro=rss_schema
			// property: name=adv_interval, type=INTEGER macro=rss_schema
			"adv_interval": rsschema.Int64Attribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=adv_interval, type=INTEGER macro=rss_schema
			// property: name=graceful_restart, type=BOOLEAN macro=rss_schema
			"graceful_restart": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=graceful_restart, type=BOOLEAN macro=rss_schema
			// property: name=hold_time, type=INTEGER macro=rss_schema
			"hold_time": rsschema.Int64Attribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=hold_time, type=INTEGER macro=rss_schema
			// property: name=id, type=STRING macro=rss_schema
			"id": rsschema.StringAttribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=id, type=STRING macro=rss_schema
			// property: name=ipv6_prefixes_to_adv_to_wan, type=ARRAY_PRIMITIVE macro=rss_schema
			"ipv6_prefixes_to_adv_to_wan": rsschema.ListAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ElementType: types.StringType,
			},
			// key name holder for attribute: name=ipv6_prefixes_to_adv_to_wan, type=ARRAY_PRIMITIVE macro=rss_schema
			// property: name=keepalive_time, type=INTEGER macro=rss_schema
			"keepalive_time": rsschema.Int64Attribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=keepalive_time, type=INTEGER macro=rss_schema
			// property: name=local_as_num, type=STRING macro=rss_schema
			"local_as_num": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=local_as_num, type=STRING macro=rss_schema
			// property: name=maximum_paths, type=INTEGER macro=rss_schema
			"maximum_paths": rsschema.Int64Attribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=maximum_paths, type=INTEGER macro=rss_schema
			// property: name=md5_secret, type=STRING macro=rss_schema
			"md5_secret": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: true,
			},
			// key name holder for attribute: name=md5_secret, type=STRING macro=rss_schema
			"md5_secret_internal_key_name": rsschema.StringAttribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// property: name=multi_hop_limit, type=INTEGER macro=rss_schema
			"multi_hop_limit": rsschema.Int64Attribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=multi_hop_limit, type=INTEGER macro=rss_schema
			// property: name=ospf_redistribution, type=ARRAY_REFERENCE macro=rss_schema
			"ospf_redistribution": rsschema.ListNestedAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
				NestedObject: rsschema.NestedAttributeObject{
					Attributes: map[string]rsschema.Attribute{
						// property: name=route_map_id, type=STRING macro=rss_schema
						"route_map_id": rsschema.StringAttribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=route_map_id, type=STRING macro=rss_schema
						// property: name=vrf_context_id, type=STRING macro=rss_schema
						"vrf_context_id": rsschema.StringAttribute{
							Required:  false,
							Computed:  false,
							Optional:  true,
							Sensitive: false,
						},
						// key name holder for attribute: name=vrf_context_id, type=STRING macro=rss_schema
					},
				},
			},
			// key name holder for attribute: name=vrf_context_id, type=STRING macro=rss_schema
			// property: name=peer_auth_type, type=STRING macro=rss_schema
			"peer_auth_type": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=peer_auth_type, type=STRING macro=rss_schema
			// property: name=peer_retry_time, type=INTEGER macro=rss_schema
			"peer_retry_time": rsschema.Int64Attribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=peer_retry_time, type=INTEGER macro=rss_schema
			// property: name=prefix_adv_type, type=STRING macro=rss_schema
			"prefix_adv_type": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=prefix_adv_type, type=STRING macro=rss_schema
			// property: name=prefix_adv_type_to_lan, type=STRING macro=rss_schema
			"prefix_adv_type_to_lan": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=prefix_adv_type_to_lan, type=STRING macro=rss_schema
			// property: name=prefixes_to_adv_to_wan, type=ARRAY_PRIMITIVE macro=rss_schema
			"prefixes_to_adv_to_wan": rsschema.ListAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ElementType: types.StringType,
			},
			// key name holder for attribute: name=prefixes_to_adv_to_wan, type=ARRAY_PRIMITIVE macro=rss_schema
			// property: name=router_id, type=STRING macro=rss_schema
			"router_id": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=router_id, type=STRING macro=rss_schema
			// property: name=stalepath_time, type=INTEGER macro=rss_schema
			"stalepath_time": rsschema.Int64Attribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=stalepath_time, type=INTEGER macro=rss_schema
		},
	}
}

// Configure prepares the struct.
func (r *sitesElementsBgpconfigsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*sdwan.Client)
}

// in some apis the status code is not consistent and hence we may have to act upon
// specific error codes instead
func (r *sitesElementsBgpconfigsResource) GetHttpStatusCode(request *sdwan_client.SdwanClientRequestResponse) int {
	if request.ResponseErrorCode == nil {
		return request.ResponseStatusCode
	}
	switch *request.ResponseErrorCode {
	case "OBJECT_NOT_FOUND":
		return 404
	default:
		return request.ResponseStatusCode
	}
}

func (r *sitesElementsBgpconfigsResource) doGet(ctx context.Context, state *rsModelBGPGlobalConfigScreenV2N4, savestate *rsModelBGPGlobalConfigScreenV2N4, State *tfsdk.State, resp *resource.ReadResponse) bool {
	// Basic logging.
	tfid := savestate.Tfid.ValueString()
	tflog.Info(ctx, "performing resource read", map[string]any{
		"terraform_provider_function": "Read",
		"resource_name":               "prismasdwan_sites_elements_bgpconfigs",
		"tfid":                        tfid,
	})

	tokens := strings.Split(tfid, IdSeparator)
	if len(tokens) != 3 {
		resp.Diagnostics.AddError("error in prismasdwan_sites_elements_bgpconfigs ID format", "Expected 3 tokens")
		return false
	}

	// Prepare to read the config.
	svc := sdwan_client.NewClient(r.client)

	// Prepare input for the API endpoint.
	read_request := &sdwan_client.SdwanClientRequestResponse{}
	read_request.Method = "GET"
	read_request.Path = "/sdwan/v2.4/api/sites/{site_id}/elements/{element_id}/bgpconfigs/{bgp_config_id}"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, savestate.TfParameters)
	read_request.PathParameters = &params
	// add last parameter as ObjectID
	(*read_request.PathParameters)["bgp_config_id"] = &tokens[0]
	// add other parameters by splitting on `=`
	for _, token := range tokens[1:] {
		param := strings.Split(token, "=")
		(*read_request.PathParameters)[param[0]] = &param[1]
	}

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, read_request)
	if read_request.ResponseErr != nil {
		if IsObjectNotFound(*read_request.ResponseErr) {
			State.RemoveResource(ctx)
		} else if r.GetHttpStatusCode(read_request) == 404 {
			State.RemoveResource(ctx)
		} else {
			tflog.Info(ctx, "read request failed for prismasdwan_sites_elements_bgpconfigs", map[string]any{
				"terraform_provider_function": "Read",
				"resource_name":               "prismasdwan_sites_elements_bgpconfigs",
				"path":                        read_request.FinalPath,
				"request":                     read_request.ToString(),
			})
			resp.Diagnostics.AddError("error reading prismasdwan_sites_elements_bgpconfigs from sdwan servers", (*read_request.ResponseErr).Error())
		}
		return false
	}

	// process http json path
	response_body_string := string(*read_request.ResponseBytes)
	// inject overrides
	response_body_string, _ = sjson.Delete(response_body_string, "_created_on_utc")
	response_body_string, _ = sjson.Set(response_body_string, "_schema", 0)

	// Store the answer to state. schema=BGPGlobalConfigScreenV2N4
	state.Tfid = savestate.Tfid
	// copy parameters from savestate as they are
	if savestate.TfParameters.IsNull() {
		state.TfParameters = types.MapNull(types.StringType)
	} else {
		state.TfParameters = savestate.TfParameters
	}
	// start copying attributes
	var ans sdwan_schema.BGPGlobalConfigScreenV2N4
	// copy from json response
	json_err := json.Unmarshal([]byte(response_body_string), &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to BGPGlobalConfigScreenV2N4 in read", json_err.Error())
		return false
	}
	// lets copy all items into state
	// copy_to_state: state=state prefix=rsModel ans=ans properties=21
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=admin_distance, type=INTEGER macro=copy_to_state
	state.AdminDistance = types.Int64PointerValue(ans.AdminDistance)
	// property: name=adv_interval, type=INTEGER macro=copy_to_state
	state.AdvInterval = types.Int64PointerValue(ans.AdvInterval)
	// property: name=graceful_restart, type=BOOLEAN macro=copy_to_state
	state.GracefulRestart = types.BoolPointerValue(ans.GracefulRestart)
	// property: name=hold_time, type=INTEGER macro=copy_to_state
	state.HoldTime = types.Int64PointerValue(ans.HoldTime)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=ipv6_prefixes_to_adv_to_wan, type=ARRAY_PRIMITIVE macro=copy_to_state
	varIpv6PrefixesToAdvToWan, errIpv6PrefixesToAdvToWan := types.ListValueFrom(ctx, types.StringType, ans.Ipv6PrefixesToAdvToWan)
	state.Ipv6PrefixesToAdvToWan = varIpv6PrefixesToAdvToWan
	resp.Diagnostics.Append(errIpv6PrefixesToAdvToWan.Errors()...)
	// property: name=keepalive_time, type=INTEGER macro=copy_to_state
	state.KeepaliveTime = types.Int64PointerValue(ans.KeepaliveTime)
	// property: name=local_as_num, type=STRING macro=copy_to_state
	state.LocalAsNum = types.StringPointerValue(ans.LocalAsNum)
	// property: name=maximum_paths, type=INTEGER macro=copy_to_state
	state.MaximumPaths = types.Int64PointerValue(ans.MaximumPaths)
	// property: name=md5_secret, type=STRING macro=copy_to_state
	encryptedMd5SecretKeyName := state.Md5SecretInternalKeyName.String()
	encryptedMd5SecretValueBytes, _ := resp.Private.GetKey(ctx, encryptedMd5SecretKeyName)
	if encryptedMd5SecretValueBytes != nil {
		decryptedMd5Secret, _ := Decrypt(string(encryptedMd5SecretValueBytes))
		state.Md5Secret = types.StringValue(decryptedMd5Secret)
	}
	// property: name=multi_hop_limit, type=INTEGER macro=copy_to_state
	state.MultiHopLimit = types.Int64PointerValue(ans.MultiHopLimit)
	// property: name=ospf_redistribution, type=ARRAY_REFERENCE macro=copy_to_state
	if ans.OspfRedistribution == nil {
		state.OspfRedistribution = nil
	} else if len(ans.OspfRedistribution) == 0 {
		state.OspfRedistribution = []rsModelOspfRedistribution{}
	} else {
		state.OspfRedistribution = make([]rsModelOspfRedistribution, 0, len(ans.OspfRedistribution))
		for varLoopOspfRedistributionIndex, varLoopOspfRedistribution := range ans.OspfRedistribution {
			// add a new item
			state.OspfRedistribution = append(state.OspfRedistribution, rsModelOspfRedistribution{})
			// copy_to_state: state=state.OspfRedistribution[varLoopOspfRedistributionIndex] prefix=rsModel ans=varLoopOspfRedistribution properties=2
			// property: name=route_map_id, type=STRING macro=copy_to_state
			state.OspfRedistribution[varLoopOspfRedistributionIndex].RouteMapId = types.StringPointerValue(varLoopOspfRedistribution.RouteMapId)
			// property: name=vrf_context_id, type=STRING macro=copy_to_state
			state.OspfRedistribution[varLoopOspfRedistributionIndex].VrfContextId = types.StringPointerValue(varLoopOspfRedistribution.VrfContextId)
		}
	}
	// property: name=peer_auth_type, type=STRING macro=copy_to_state
	state.PeerAuthType = types.StringPointerValue(ans.PeerAuthType)
	// property: name=peer_retry_time, type=INTEGER macro=copy_to_state
	state.PeerRetryTime = types.Int64PointerValue(ans.PeerRetryTime)
	// property: name=prefix_adv_type, type=STRING macro=copy_to_state
	state.PrefixAdvType = types.StringPointerValue(ans.PrefixAdvType)
	// property: name=prefix_adv_type_to_lan, type=STRING macro=copy_to_state
	state.PrefixAdvTypeToLan = types.StringPointerValue(ans.PrefixAdvTypeToLan)
	// property: name=prefixes_to_adv_to_wan, type=ARRAY_PRIMITIVE macro=copy_to_state
	varPrefixesToAdvToWan, errPrefixesToAdvToWan := types.ListValueFrom(ctx, types.StringType, ans.PrefixesToAdvToWan)
	state.PrefixesToAdvToWan = varPrefixesToAdvToWan
	resp.Diagnostics.Append(errPrefixesToAdvToWan.Errors()...)
	// property: name=router_id, type=STRING macro=copy_to_state
	state.RouterId = types.StringPointerValue(ans.RouterId)
	// property: name=stalepath_time, type=INTEGER macro=copy_to_state
	state.StalepathTime = types.Int64PointerValue(ans.StalepathTime)
	return true
}

func (r *sitesElementsBgpconfigsResource) doPut(ctx context.Context, plan *rsModelBGPGlobalConfigScreenV2N4, state *rsModelBGPGlobalConfigScreenV2N4, State *tfsdk.State, resp *resource.UpdateResponse) bool {
	state_tfid := state.Tfid.ValueString()
	plan_tfid := plan.Tfid.ValueString()
	// Basic logging.
	tflog.Info(ctx, "performing resource update", map[string]any{
		"terraform_provider_function": "Update",
		"resource_name":               "prismasdwan_sites_elements_bgpconfigs",
		"state_tfid":                  state_tfid,
		"plan_tfid":                   plan_tfid,
	})

	// both TFID must be SAME!!!
	if state_tfid != plan_tfid {
		resp.Diagnostics.AddError("error updating prismasdwan_sites_elements_bgpconfigs", "state and plan TFID do not match")
		return false
	}

	// split tokens
	tokens := strings.Split(state_tfid, IdSeparator)
	if len(tokens) != 3 {
		resp.Diagnostics.AddError("error in prismasdwan_sites_elements_bgpconfigs ID format", "Expected 3 tokens")
		return false
	}

	// Prepare input for the API endpoint.
	put_request := &sdwan_client.SdwanClientRequestResponse{}
	put_request.Method = "PUT"
	put_request.Path = "/sdwan/v2.4/api/sites/{site_id}/elements/{element_id}/bgpconfigs/{bgp_config_id}"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, state.TfParameters)
	put_request.PathParameters = &params
	// add last parameter as ObjectID
	(*put_request.PathParameters)["bgp_config_id"] = &tokens[0]
	// add other parameters by splitting on `=`
	for _, token := range tokens[1:] {
		param := strings.Split(token, "=")
		(*put_request.PathParameters)[param[0]] = &param[1]
	}

	// Client that will perform the request.
	svc := sdwan_client.NewClient(r.client)

	// prepare request from state
	var body = &sdwan_schema.BGPGlobalConfigScreenV2N4{}

	// now we create the JSON request from the state/plan created by TF
	// below copy code generated from macro copy_from_plan_or_state
	// copy_from_plan_or_state: body=body prefix=rsModel state=state plan=plan properties=21
	// property: name=_etag, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.Etag = ValueInt64PointerFromPlanOrState(plan.Etag, state.Etag)
	} else {
		body.Etag = Int64ValueOrNil(plan.Etag)
	}
	// property: name=_schema, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.Schema = ValueInt64PointerFromPlanOrState(plan.Schema, state.Schema)
	} else {
		body.Schema = Int64ValueOrNil(plan.Schema)
	}
	// property: name=admin_distance, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.AdminDistance = ValueInt64PointerFromPlanOrState(plan.AdminDistance, state.AdminDistance)
	} else {
		body.AdminDistance = Int64ValueOrNil(plan.AdminDistance)
	}
	// property: name=adv_interval, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.AdvInterval = ValueInt64PointerFromPlanOrState(plan.AdvInterval, state.AdvInterval)
	} else {
		body.AdvInterval = Int64ValueOrNil(plan.AdvInterval)
	}
	// property: name=graceful_restart, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.GracefulRestart = ValueBoolPointerFromPlanOrState(plan.GracefulRestart, state.GracefulRestart)
	} else {
		body.GracefulRestart = BoolValueOrNil(plan.GracefulRestart)
	}
	// property: name=hold_time, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.HoldTime = ValueInt64PointerFromPlanOrState(plan.HoldTime, state.HoldTime)
	} else {
		body.HoldTime = Int64ValueOrNil(plan.HoldTime)
	}
	// property: name=id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Id = ValueStringPointerFromPlanOrState(plan.Id, state.Id)
	} else {
		body.Id = StringValueOrNil(plan.Id)
	}
	// property: name=ipv6_prefixes_to_adv_to_wan, type=ARRAY_PRIMITIVE macro=copy_from_plan_or_state
	body.Ipv6PrefixesToAdvToWan = ListStringValueOrNil(ctx, plan.Ipv6PrefixesToAdvToWan)
	// property: name=keepalive_time, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.KeepaliveTime = ValueInt64PointerFromPlanOrState(plan.KeepaliveTime, state.KeepaliveTime)
	} else {
		body.KeepaliveTime = Int64ValueOrNil(plan.KeepaliveTime)
	}
	// property: name=local_as_num, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.LocalAsNum = ValueStringPointerFromPlanOrState(plan.LocalAsNum, state.LocalAsNum)
	} else {
		body.LocalAsNum = StringValueOrNil(plan.LocalAsNum)
	}
	// property: name=maximum_paths, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.MaximumPaths = ValueInt64PointerFromPlanOrState(plan.MaximumPaths, state.MaximumPaths)
	} else {
		body.MaximumPaths = Int64ValueOrNil(plan.MaximumPaths)
	}
	// property: name=md5_secret, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Md5Secret = ValueStringPointerFromPlanOrState(plan.Md5Secret, state.Md5Secret)
	} else {
		body.Md5Secret = StringValueOrNil(plan.Md5Secret)
	}
	// property: name=multi_hop_limit, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.MultiHopLimit = ValueInt64PointerFromPlanOrState(plan.MultiHopLimit, state.MultiHopLimit)
	} else {
		body.MultiHopLimit = Int64ValueOrNil(plan.MultiHopLimit)
	}
	// property: name=ospf_redistribution, type=ARRAY_REFERENCE macro=copy_from_plan_or_state
	if plan.OspfRedistribution == nil && (state == nil || state.OspfRedistribution == nil) {
		body.OspfRedistribution = nil
	} else if len(plan.OspfRedistribution) == 0 && (state == nil || len(state.OspfRedistribution) == 0) {
		body.OspfRedistribution = []sdwan_schema.OspfRedistribution{}
	} else if len(plan.OspfRedistribution) != 0 || (state != nil && len(state.OspfRedistribution) != 0) {
		OspfRedistributionToUse := plan.OspfRedistribution
		if len(plan.OspfRedistribution) == 0 {
			OspfRedistributionToUse = state.OspfRedistribution
		}
		body.OspfRedistribution = make([]sdwan_schema.OspfRedistribution, 0, len(OspfRedistributionToUse))
		for varLoopOspfRedistributionIndex, varLoopOspfRedistribution := range OspfRedistributionToUse {
			// add a new item
			body.OspfRedistribution = append(body.OspfRedistribution, sdwan_schema.OspfRedistribution{})
			// since we have chosen to stick with either the plan or state, we need to simply copy child properties
			// copy_from_plan: body=body.OspfRedistribution[varLoopOspfRedistributionIndex] prefix=rsModel plan=varLoopOspfRedistribution properties=2
			// property: name=route_map_id, type=STRING macro=copy_from_plan
			body.OspfRedistribution[varLoopOspfRedistributionIndex].RouteMapId = StringValueOrNil(varLoopOspfRedistribution.RouteMapId)
			// property: name=vrf_context_id, type=STRING macro=copy_from_plan
			body.OspfRedistribution[varLoopOspfRedistributionIndex].VrfContextId = StringValueOrNil(varLoopOspfRedistribution.VrfContextId)
		}
	}
	// property: name=peer_auth_type, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.PeerAuthType = ValueStringPointerFromPlanOrState(plan.PeerAuthType, state.PeerAuthType)
	} else {
		body.PeerAuthType = StringValueOrNil(plan.PeerAuthType)
	}
	// property: name=peer_retry_time, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.PeerRetryTime = ValueInt64PointerFromPlanOrState(plan.PeerRetryTime, state.PeerRetryTime)
	} else {
		body.PeerRetryTime = Int64ValueOrNil(plan.PeerRetryTime)
	}
	// property: name=prefix_adv_type, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.PrefixAdvType = ValueStringPointerFromPlanOrState(plan.PrefixAdvType, state.PrefixAdvType)
	} else {
		body.PrefixAdvType = StringValueOrNil(plan.PrefixAdvType)
	}
	// property: name=prefix_adv_type_to_lan, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.PrefixAdvTypeToLan = ValueStringPointerFromPlanOrState(plan.PrefixAdvTypeToLan, state.PrefixAdvTypeToLan)
	} else {
		body.PrefixAdvTypeToLan = StringValueOrNil(plan.PrefixAdvTypeToLan)
	}
	// property: name=prefixes_to_adv_to_wan, type=ARRAY_PRIMITIVE macro=copy_from_plan_or_state
	body.PrefixesToAdvToWan = ListStringValueOrNil(ctx, plan.PrefixesToAdvToWan)
	// property: name=router_id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.RouterId = ValueStringPointerFromPlanOrState(plan.RouterId, state.RouterId)
	} else {
		body.RouterId = StringValueOrNil(plan.RouterId)
	}
	// property: name=stalepath_time, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.StalepathTime = ValueInt64PointerFromPlanOrState(plan.StalepathTime, state.StalepathTime)
	} else {
		body.StalepathTime = Int64ValueOrNil(plan.StalepathTime)
	}

	// convert body to map
	json_body, err := json.Marshal(body)
	if err != nil {
		resp.Diagnostics.AddError("error marshaling struct BGPGlobalConfigScreenV2N4 to JSON:", err.Error())
		return false
	}

	// process http json path
	request_body_string := string(json_body)
	// copy pointer
	put_request.RequestBody = &request_body_string

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, put_request)
	if put_request.ResponseErr != nil {
		if IsObjectNotFound(*put_request.ResponseErr) {
			State.RemoveResource(ctx)
		} else if r.GetHttpStatusCode(put_request) == 404 {
			State.RemoveResource(ctx)
		} else {
			tflog.Info(ctx, "update request failed for prismasdwan_sites_elements_bgpconfigs", map[string]any{
				"terraform_provider_function": "Update",
				"resource_name":               "prismasdwan_sites_elements_bgpconfigs",
				"path":                        put_request.FinalPath,
			})
			tflog.Debug(ctx, "update request failed for prismasdwan_sites_elements_bgpconfigs", map[string]any{
				"terraform_provider_function": "Update",
				"resource_name":               "prismasdwan_sites_elements_bgpconfigs",
				"path":                        put_request.FinalPath,
				"request":                     put_request.ToString(),
			})
			resp.Diagnostics.AddError("error updating prismasdwan_sites_elements_bgpconfigs", (*put_request.ResponseErr).Error())
		}
		return false
	}

	// process http json path
	response_body_string := string(*put_request.ResponseBytes)
	// inject overrides
	response_body_string, _ = sjson.Delete(response_body_string, "_created_on_utc")
	response_body_string, _ = sjson.Set(response_body_string, "_schema", 0)

	// start copying attributes
	var ans sdwan_schema.BGPGlobalConfigScreenV2N4
	// copy from json response
	json_err := json.Unmarshal([]byte(response_body_string), &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to BGPGlobalConfigScreenV2N4 in update", json_err.Error())
		return false
	}

	// Store the answer to state. schema=BGPGlobalConfigScreenV2N4
	// copy_to_state: state=state prefix=rsModel ans=ans properties=21
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=admin_distance, type=INTEGER macro=copy_to_state
	state.AdminDistance = types.Int64PointerValue(ans.AdminDistance)
	// property: name=adv_interval, type=INTEGER macro=copy_to_state
	state.AdvInterval = types.Int64PointerValue(ans.AdvInterval)
	// property: name=graceful_restart, type=BOOLEAN macro=copy_to_state
	state.GracefulRestart = types.BoolPointerValue(ans.GracefulRestart)
	// property: name=hold_time, type=INTEGER macro=copy_to_state
	state.HoldTime = types.Int64PointerValue(ans.HoldTime)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=ipv6_prefixes_to_adv_to_wan, type=ARRAY_PRIMITIVE macro=copy_to_state
	varIpv6PrefixesToAdvToWan, errIpv6PrefixesToAdvToWan := types.ListValueFrom(ctx, types.StringType, ans.Ipv6PrefixesToAdvToWan)
	state.Ipv6PrefixesToAdvToWan = varIpv6PrefixesToAdvToWan
	resp.Diagnostics.Append(errIpv6PrefixesToAdvToWan.Errors()...)
	// property: name=keepalive_time, type=INTEGER macro=copy_to_state
	state.KeepaliveTime = types.Int64PointerValue(ans.KeepaliveTime)
	// property: name=local_as_num, type=STRING macro=copy_to_state
	state.LocalAsNum = types.StringPointerValue(ans.LocalAsNum)
	// property: name=maximum_paths, type=INTEGER macro=copy_to_state
	state.MaximumPaths = types.Int64PointerValue(ans.MaximumPaths)
	// property: name=md5_secret, type=STRING macro=copy_to_state
	state.Md5Secret = types.StringPointerValue(plan.Md5Secret.ValueStringPointer())
	// this property is sensitive and will be stored in the state's internal key name
	state.Md5SecretInternalKeyName = types.StringValue(GenerateRandomString(16))
	// store value if needed
	if !state.Md5Secret.IsNull() {
		encryptedMd5Secret, _ := Encrypt([]byte(state.Md5Secret.String()))
		resp.Private.SetKey(ctx, state.Md5SecretInternalKeyName.String(), []byte(encryptedMd5Secret))
	}
	// property: name=multi_hop_limit, type=INTEGER macro=copy_to_state
	state.MultiHopLimit = types.Int64PointerValue(ans.MultiHopLimit)
	// property: name=ospf_redistribution, type=ARRAY_REFERENCE macro=copy_to_state
	if ans.OspfRedistribution == nil {
		state.OspfRedistribution = nil
	} else if len(ans.OspfRedistribution) == 0 {
		state.OspfRedistribution = []rsModelOspfRedistribution{}
	} else {
		state.OspfRedistribution = make([]rsModelOspfRedistribution, 0, len(ans.OspfRedistribution))
		for varLoopOspfRedistributionIndex, varLoopOspfRedistribution := range ans.OspfRedistribution {
			// add a new item
			state.OspfRedistribution = append(state.OspfRedistribution, rsModelOspfRedistribution{})
			// copy_to_state: state=state.OspfRedistribution[varLoopOspfRedistributionIndex] prefix=rsModel ans=varLoopOspfRedistribution properties=2
			// property: name=route_map_id, type=STRING macro=copy_to_state
			state.OspfRedistribution[varLoopOspfRedistributionIndex].RouteMapId = types.StringPointerValue(varLoopOspfRedistribution.RouteMapId)
			// property: name=vrf_context_id, type=STRING macro=copy_to_state
			state.OspfRedistribution[varLoopOspfRedistributionIndex].VrfContextId = types.StringPointerValue(varLoopOspfRedistribution.VrfContextId)
		}
	}
	// property: name=peer_auth_type, type=STRING macro=copy_to_state
	state.PeerAuthType = types.StringPointerValue(ans.PeerAuthType)
	// property: name=peer_retry_time, type=INTEGER macro=copy_to_state
	state.PeerRetryTime = types.Int64PointerValue(ans.PeerRetryTime)
	// property: name=prefix_adv_type, type=STRING macro=copy_to_state
	state.PrefixAdvType = types.StringPointerValue(ans.PrefixAdvType)
	// property: name=prefix_adv_type_to_lan, type=STRING macro=copy_to_state
	state.PrefixAdvTypeToLan = types.StringPointerValue(ans.PrefixAdvTypeToLan)
	// property: name=prefixes_to_adv_to_wan, type=ARRAY_PRIMITIVE macro=copy_to_state
	varPrefixesToAdvToWan, errPrefixesToAdvToWan := types.ListValueFrom(ctx, types.StringType, ans.PrefixesToAdvToWan)
	state.PrefixesToAdvToWan = varPrefixesToAdvToWan
	resp.Diagnostics.Append(errPrefixesToAdvToWan.Errors()...)
	// property: name=router_id, type=STRING macro=copy_to_state
	state.RouterId = types.StringPointerValue(ans.RouterId)
	// property: name=stalepath_time, type=INTEGER macro=copy_to_state
	state.StalepathTime = types.Int64PointerValue(ans.StalepathTime)
	return true
}

// Performs the Create(POST) Operation on the Resource
// TfID is pulled from plan to use in the creation request
// Path Parameters are encoded into TfID itself
func (r *sitesElementsBgpconfigsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Info(ctx, "executing resource create for prismasdwan_sites_elements_bgpconfigs")
	var plan rsModelBGPGlobalConfigScreenV2N4
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// this resource does not have a POST call defined, assuming that the PUT call is present and GET call is present
	// path=/sdwan/v2.4/api/sites/{site_id}/elements/{element_id}/bgpconfigs/{bgp_config_id}

	// state in api servers
	var save rsModelBGPGlobalConfigScreenV2N4

	// create a new tfid
	var idBuilder strings.Builder
	params := MapStringValueOrNil(ctx, plan.TfParameters)
	// ensure all parameters are written
	site_id, ok := params["site_id"]
	if !ok {
		resp.Diagnostics.AddError("could not find site_id in x_parameters", "missing parameter")
		return
	}
	idBuilder.WriteString(IdSeparator)
	idBuilder.WriteString("site_id")
	idBuilder.WriteString("=")
	idBuilder.WriteString(*site_id)
	element_id, ok := params["element_id"]
	if !ok {
		resp.Diagnostics.AddError("could not find element_id in x_parameters", "missing parameter")
		return
	}
	idBuilder.WriteString(IdSeparator)
	idBuilder.WriteString("element_id")
	idBuilder.WriteString("=")
	idBuilder.WriteString(*element_id)
	bgp_config_id, ok := params["bgp_config_id"]
	if !ok {
		resp.Diagnostics.AddError("could not find bgp_config_id in x_parameters", "missing parameter")
		return
	}
	idBuilder.WriteString(IdSeparator)
	idBuilder.WriteString("bgp_config_id")
	idBuilder.WriteString("=")
	idBuilder.WriteString(*bgp_config_id)
	// both TFID MUST MATCH!
	plan.Tfid = types.StringValue(idBuilder.String())
	save.Tfid = types.StringValue(idBuilder.String())
	// make a get call instead
	gResp := resource.ReadResponse{
		Private:     resp.Private,
		Diagnostics: resp.Diagnostics,
	}
	if r.doGet(ctx, &save, &plan, &resp.State, &gResp) {
		// make a put to override
		uResp := resource.UpdateResponse{
			Private:     resp.Private,
			Diagnostics: resp.Diagnostics,
		}
		if r.doPut(ctx, &plan, &save, &resp.State, &uResp) {
			// push into state
			resp.Diagnostics.Append(resp.State.Set(ctx, &save)...)
		}
	}
}

// Performs the Read(GET) Operation on the Resource
// TfID is pulled from state to use in the read request
// Path Parameters are extracted TfID itself
func (r *sitesElementsBgpconfigsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {

	tflog.Info(ctx, "executing resource read for prismasdwan_sites_elements_bgpconfigs")
	var savestate, state rsModelBGPGlobalConfigScreenV2N4
	resp.Diagnostics.Append(req.State.Get(ctx, &savestate)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make a get call
	if r.doGet(ctx, &state, &savestate, &resp.State, resp) {
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	}
}

// Performs the Update(PUT) Operation on the Resource
// TfID is pulled from state to use in the read request
// Path Parameters are extracted TfID itself
// TfID must match in state and plan, else error is thrown
func (r *sitesElementsBgpconfigsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {

	tflog.Info(ctx, "executing resource update for prismasdwan_sites_elements_bgpconfigs")
	var plan, state rsModelBGPGlobalConfigScreenV2N4
	// copy state from TF
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// copy plan from TF
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make a put call
	if r.doPut(ctx, &plan, &state, &resp.State, resp) {
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	}
}

// Performs the Delete Operation on the Resource
// TfID is pulled from state to use in the deletion request
// Path Parameters are extracted from the TfID itself
func (r *sitesElementsBgpconfigsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {

	tflog.Info(ctx, "executing resource delete for prismasdwan_sites_elements_bgpconfigs")
	// some resources are auto deleted
	resp.State.RemoveResource(ctx)
}

func (r *sitesElementsBgpconfigsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("tfid"), req, resp)
}
