package provider

// Note:  This file is automatically generated.  Manually made changes
// will be overwritten when the provider is generated.

import (
	"context"
	"encoding/json"
	"strings"

	sdwan "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk"
	sdwan_schema "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/schemas"
	sdwan_client "github.com/paloaltonetworks/terraform-provider-prismasdwan/sdk/sdwan/services"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	rsschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/tidwall/sjson"
)

// +-----------------------------------------------------------------
// | Schema Map Summary (size=goLangStructMap=3)
// | Computed Resource Name=waninterfacelabels
// +-----------------------------------------------------------------
// | WANL3Reachability HasID=false
// | VPNLinkConfiguration HasID=false
// | WANInterfaceLabelScreenV2N5 HasID=true
// +-----------------------------------------------------------------

// Resource.
var (
	_ resource.Resource                = &wanInterfaceLabelResource{}
	_ resource.ResourceWithConfigure   = &wanInterfaceLabelResource{}
	_ resource.ResourceWithImportState = &wanInterfaceLabelResource{}
)

// To enable this data source for TF Provider, go to `provider.go` and inject this into the function
// as below:
//
//	func (p *SdwanProvider) Resources(_ context.Context) []func() resource.Resource {
//	  	return []func() resource.Resource{
//	     ... <other existing resources>
//	     NewWanInterfaceLabelResource,
//	     // -- append next resource above -- //
//	     }
//	  }
func NewWanInterfaceLabelResource() resource.Resource {
	return &wanInterfaceLabelResource{}
}

type wanInterfaceLabelResource struct {
	client *sdwan.Client
}

// Metadata returns the data source type name.
func (r *wanInterfaceLabelResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = "prismasdwan_wan_interface_label"
}

// Schema defines the schema for this data source.
func (r *wanInterfaceLabelResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = rsschema.Schema{
		Description: "Retrieves a config item.",
		Attributes: map[string]rsschema.Attribute{
			"tfid": rsschema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			// rest all properties to be read from GET API Schema schema=WANInterfaceLabelScreenV2N5
			// generic x_parameters is added to accomodate path parameters
			"x_parameters": rsschema.MapAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				ElementType: types.StringType,
			},
			// property: name=_etag, type=INTEGER macro=rss_schema
			"x_etag": rsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_etag, type=INTEGER macro=rss_schema
			// property: name=_schema, type=INTEGER macro=rss_schema
			"x_schema": rsschema.Int64Attribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=_schema, type=INTEGER macro=rss_schema
			// property: name=bwc_enabled, type=BOOLEAN macro=rss_schema
			"bwc_enabled": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=bwc_enabled, type=BOOLEAN macro=rss_schema
			// property: name=description, type=STRING macro=rss_schema
			"description": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=description, type=STRING macro=rss_schema
			// property: name=id, type=STRING macro=rss_schema
			"id": rsschema.StringAttribute{
				Required:  false,
				Computed:  true,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=id, type=STRING macro=rss_schema
			// property: name=l3_reachability, type=REFERENCE macro=rss_schema
			"l3_reachability": rsschema.SingleNestedAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
				Attributes: map[string]rsschema.Attribute{
					// property: name=probe_config_ids, type=ARRAY_PRIMITIVE macro=rss_schema
					"probe_config_ids": rsschema.ListAttribute{
						Required:    false,
						Computed:    false,
						Optional:    true,
						Sensitive:   false,
						ElementType: types.StringType,
					},
					// key name holder for attribute: name=probe_config_ids, type=ARRAY_PRIMITIVE macro=rss_schema
					// property: name=use_element_default, type=BOOLEAN macro=rss_schema
					"use_element_default": rsschema.BoolAttribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=use_element_default, type=BOOLEAN macro=rss_schema
				},
			},
			// key name holder for attribute: name=use_element_default, type=BOOLEAN macro=rss_schema
			// property: name=label, type=STRING macro=rss_schema
			"label": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=label, type=STRING macro=rss_schema
			// property: name=lqm_enabled, type=BOOLEAN macro=rss_schema
			"lqm_enabled": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=lqm_enabled, type=BOOLEAN macro=rss_schema
			// property: name=name, type=STRING macro=rss_schema
			"name": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=name, type=STRING macro=rss_schema
			// property: name=probe_profile_id, type=STRING macro=rss_schema
			"probe_profile_id": rsschema.StringAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=probe_profile_id, type=STRING macro=rss_schema
			// property: name=tags, type=SET_PRIMITIVE macro=rss_schema
			"tags": rsschema.SetAttribute{
				Required:    false,
				Computed:    false,
				Optional:    true,
				Sensitive:   false,
				ElementType: types.StringType,
			},
			// key name holder for attribute: name=tags, type=SET_PRIMITIVE macro=rss_schema
			// property: name=use_for_application_reachability_probes, type=BOOLEAN macro=rss_schema
			"use_for_application_reachability_probes": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=use_for_application_reachability_probes, type=BOOLEAN macro=rss_schema
			// property: name=use_for_controller_connections, type=BOOLEAN macro=rss_schema
			"use_for_controller_connections": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=use_for_controller_connections, type=BOOLEAN macro=rss_schema
			// property: name=use_lqm_for_non_hub_paths, type=BOOLEAN macro=rss_schema
			"use_lqm_for_non_hub_paths": rsschema.BoolAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
			},
			// key name holder for attribute: name=use_lqm_for_non_hub_paths, type=BOOLEAN macro=rss_schema
			// property: name=vpnlink_configuration, type=REFERENCE macro=rss_schema
			"vpnlink_configuration": rsschema.SingleNestedAttribute{
				Required:  false,
				Computed:  false,
				Optional:  true,
				Sensitive: false,
				Attributes: map[string]rsschema.Attribute{
					// property: name=keep_alive_failure_count, type=INTEGER macro=rss_schema
					"keep_alive_failure_count": rsschema.Int64Attribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=keep_alive_failure_count, type=INTEGER macro=rss_schema
					// property: name=keep_alive_interval, type=INTEGER macro=rss_schema
					"keep_alive_interval": rsschema.Int64Attribute{
						Required:  false,
						Computed:  false,
						Optional:  true,
						Sensitive: false,
					},
					// key name holder for attribute: name=keep_alive_interval, type=INTEGER macro=rss_schema
				},
			},
			// key name holder for attribute: name=keep_alive_interval, type=INTEGER macro=rss_schema
		},
	}
}

// Configure prepares the struct.
func (r *wanInterfaceLabelResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(*sdwan.Client)
}

// in some apis the status code is not consistent and hence we may have to act upon
// specific error codes instead
func (r *wanInterfaceLabelResource) GetHttpStatusCode(request *sdwan_client.SdwanClientRequestResponse) int {
	if request.ResponseErrorCode == nil {
		return request.ResponseStatusCode
	}
	switch *request.ResponseErrorCode {
	case "OBJECT_NOT_FOUND":
		return 404
	default:
		return request.ResponseStatusCode
	}
}

func (r *wanInterfaceLabelResource) doGet(ctx context.Context, state *rsModelWANInterfaceLabelScreenV2N5, savestate *rsModelWANInterfaceLabelScreenV2N5, State *tfsdk.State, resp *resource.ReadResponse) bool {
	// Basic logging.
	tfid := savestate.Tfid.ValueString()
	tflog.Info(ctx, "performing resource read", map[string]any{
		"terraform_provider_function": "Read",
		"resource_name":               "prismasdwan_wan_interface_label",
		"tfid":                        tfid,
	})

	tokens := strings.Split(tfid, IdSeparator)
	if len(tokens) != 1 {
		resp.Diagnostics.AddError("error in prismasdwan_wan_interface_label ID format", "Expected 1 tokens")
		return false
	}

	// Prepare to read the config.
	svc := sdwan_client.NewClient(r.client)

	// Prepare input for the API endpoint.
	read_request := &sdwan_client.SdwanClientRequestResponse{}
	read_request.ResourceType = "prismasdwan_wan_interface_label"
	read_request.Method = "GET"
	read_request.Path = "/sdwan/v2.5/api/waninterfacelabels/{wantinterface_label_id}"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, savestate.TfParameters)
	read_request.PathParameters = &params
	// add last parameter as ObjectID
	(*read_request.PathParameters)["wantinterface_label_id"] = &tokens[0]
	// add other parameters by splitting on `=`
	for _, token := range tokens[1:] {
		param := strings.Split(token, "=")
		(*read_request.PathParameters)[param[0]] = &param[1]
	}

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, read_request)
	if read_request.ResponseErr != nil {
		if IsObjectNotFound(*read_request.ResponseErr) {
			State.RemoveResource(ctx)
		} else if r.GetHttpStatusCode(read_request) == 404 {
			State.RemoveResource(ctx)
		} else {
			tflog.Info(ctx, "read request failed for prismasdwan_wan_interface_label", map[string]any{
				"terraform_provider_function": "Read",
				"resource_name":               "prismasdwan_wan_interface_label",
				"path":                        read_request.FinalPath,
				"request":                     read_request.ToString(),
			})
			resp.Diagnostics.AddError("error reading prismasdwan_wan_interface_label from sdwan servers", (*read_request.ResponseErr).Error())
		}
		return false
	}

	// process http json path
	response_body_string := string(*read_request.ResponseBytes)
	// inject overrides
	response_body_string, _ = sjson.Delete(response_body_string, "_created_on_utc")
	response_body_string, _ = sjson.Set(response_body_string, "_schema", 0)

	// Store the answer to state. schema=WANInterfaceLabelScreenV2N5
	state.Tfid = savestate.Tfid
	// copy parameters from savestate as they are
	if savestate.TfParameters.IsNull() {
		state.TfParameters = types.MapNull(types.StringType)
	} else {
		state.TfParameters = savestate.TfParameters
	}
	// start copying attributes
	var ans sdwan_schema.WANInterfaceLabelScreenV2N5
	// copy from json response
	json_err := json.Unmarshal([]byte(response_body_string), &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to WANInterfaceLabelScreenV2N5 in read", json_err.Error())
		return false
	}
	// lets copy all items into state
	// copy_to_state: state=state prefix=rsModel ans=ans properties=15
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=bwc_enabled, type=BOOLEAN macro=copy_to_state
	state.BwcEnabled = types.BoolPointerValue(ans.BwcEnabled)
	// property: name=description, type=STRING macro=copy_to_state
	state.Description = types.StringPointerValue(ans.Description)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=l3_reachability, type=REFERENCE macro=copy_to_state
	if ans.L3Reachability == nil {
		state.L3Reachability = nil
	} else {
		state.L3Reachability = &rsModelWANL3Reachability{}
		// copy_to_state: state=state.L3Reachability prefix=rsModel ans=ans.L3Reachability properties=2
		// property: name=probe_config_ids, type=ARRAY_PRIMITIVE macro=copy_to_state
		varProbeConfigIds, errProbeConfigIds := types.ListValueFrom(ctx, types.StringType, ans.L3Reachability.ProbeConfigIds)
		state.L3Reachability.ProbeConfigIds = varProbeConfigIds
		resp.Diagnostics.Append(errProbeConfigIds.Errors()...)
		// property: name=use_element_default, type=BOOLEAN macro=copy_to_state
		state.L3Reachability.UseElementDefault = types.BoolPointerValue(ans.L3Reachability.UseElementDefault)
	}
	// property: name=label, type=STRING macro=copy_to_state
	state.Label = types.StringPointerValue(ans.Label)
	// property: name=lqm_enabled, type=BOOLEAN macro=copy_to_state
	state.LqmEnabled = types.BoolPointerValue(ans.LqmEnabled)
	// property: name=name, type=STRING macro=copy_to_state
	state.Name = types.StringPointerValue(ans.Name)
	// property: name=probe_profile_id, type=STRING macro=copy_to_state
	state.ProbeProfileId = types.StringPointerValue(ans.ProbeProfileId)
	// property: name=tags, type=SET_PRIMITIVE macro=copy_to_state
	varTags, errTags := types.SetValueFrom(ctx, types.StringType, ans.Tags)
	state.Tags = varTags
	resp.Diagnostics.Append(errTags.Errors()...)
	// property: name=use_for_application_reachability_probes, type=BOOLEAN macro=copy_to_state
	state.UseForApplicationReachabilityProbes = types.BoolPointerValue(ans.UseForApplicationReachabilityProbes)
	// property: name=use_for_controller_connections, type=BOOLEAN macro=copy_to_state
	state.UseForControllerConnections = types.BoolPointerValue(ans.UseForControllerConnections)
	// property: name=use_lqm_for_non_hub_paths, type=BOOLEAN macro=copy_to_state
	state.UseLqmForNonHubPaths = types.BoolPointerValue(ans.UseLqmForNonHubPaths)
	// property: name=vpnlink_configuration, type=REFERENCE macro=copy_to_state
	if ans.VpnlinkConfiguration == nil {
		state.VpnlinkConfiguration = nil
	} else {
		state.VpnlinkConfiguration = &rsModelVPNLinkConfiguration{}
		// copy_to_state: state=state.VpnlinkConfiguration prefix=rsModel ans=ans.VpnlinkConfiguration properties=2
		// property: name=keep_alive_failure_count, type=INTEGER macro=copy_to_state
		state.VpnlinkConfiguration.KeepAliveFailureCount = types.Int64PointerValue(ans.VpnlinkConfiguration.KeepAliveFailureCount)
		// property: name=keep_alive_interval, type=INTEGER macro=copy_to_state
		state.VpnlinkConfiguration.KeepAliveInterval = types.Int64PointerValue(ans.VpnlinkConfiguration.KeepAliveInterval)
	}
	return true
}

func (r *wanInterfaceLabelResource) doPut(ctx context.Context, plan *rsModelWANInterfaceLabelScreenV2N5, state *rsModelWANInterfaceLabelScreenV2N5, State *tfsdk.State, resp *resource.UpdateResponse) bool {
	state_tfid := state.Tfid.ValueString()
	plan_tfid := plan.Tfid.ValueString()
	// Basic logging.
	tflog.Info(ctx, "performing resource update", map[string]any{
		"terraform_provider_function": "Update",
		"resource_name":               "prismasdwan_wan_interface_label",
		"state_tfid":                  state_tfid,
		"plan_tfid":                   plan_tfid,
	})

	// both TFID must be SAME!!!
	if state_tfid != plan_tfid {
		resp.Diagnostics.AddError("error updating prismasdwan_wan_interface_label", "state and plan TFID do not match")
		return false
	}

	// split tokens
	tokens := strings.Split(state_tfid, IdSeparator)
	if len(tokens) != 1 {
		resp.Diagnostics.AddError("error in prismasdwan_wan_interface_label ID format", "Expected 1 tokens")
		return false
	}

	// Prepare input for the API endpoint.
	put_request := &sdwan_client.SdwanClientRequestResponse{}
	put_request.ResourceType = "prismasdwan_wan_interface_label"
	put_request.Method = "PUT"
	put_request.Path = "/sdwan/v2.5/api/waninterfacelabels/{wantinterface_label_id}"

	// copy parameters from plan always
	params := MapStringValueOrNil(ctx, state.TfParameters)
	put_request.PathParameters = &params
	// add last parameter as ObjectID
	(*put_request.PathParameters)["wantinterface_label_id"] = &tokens[0]
	// add other parameters by splitting on `=`
	for _, token := range tokens[1:] {
		param := strings.Split(token, "=")
		(*put_request.PathParameters)[param[0]] = &param[1]
	}

	// Client that will perform the request.
	svc := sdwan_client.NewClient(r.client)

	// prepare request from state
	var body = &sdwan_schema.WANInterfaceLabelScreenV2N5{}

	// now we create the JSON request from the state/plan created by TF
	// below copy code generated from macro copy_from_plan_or_state
	// copy_from_plan_or_state: body=body prefix=rsModel state=state plan=plan properties=15
	// property: name=_etag, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.Etag = ValueInt64PointerFromPlanOrState(plan.Etag, state.Etag)
	} else {
		body.Etag = Int64ValueOrNil(plan.Etag)
	}
	// property: name=_schema, type=INTEGER macro=copy_from_plan_or_state
	if state != nil {
		body.Schema = ValueInt64PointerFromPlanOrState(plan.Schema, state.Schema)
	} else {
		body.Schema = Int64ValueOrNil(plan.Schema)
	}
	// property: name=bwc_enabled, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.BwcEnabled = ValueBoolPointerFromPlanOrState(plan.BwcEnabled, state.BwcEnabled)
	} else {
		body.BwcEnabled = BoolValueOrNil(plan.BwcEnabled)
	}
	// property: name=description, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Description = ValueStringPointerFromPlanOrState(plan.Description, state.Description)
	} else {
		body.Description = StringValueOrNil(plan.Description)
	}
	// property: name=id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Id = ValueStringPointerFromPlanOrState(plan.Id, state.Id)
	} else {
		body.Id = StringValueOrNil(plan.Id)
	}
	// property: name=l3_reachability, type=REFERENCE macro=copy_from_plan_or_state
	if plan.L3Reachability == nil {
		body.L3Reachability = nil
	} else {
		body.L3Reachability = &sdwan_schema.WANL3Reachability{}
		// copy_from_plan_or_state: body=body.L3Reachability prefix=rsModel state=state.L3Reachability plan=plan.L3Reachability properties=2
		// property: name=probe_config_ids, type=ARRAY_PRIMITIVE macro=copy_from_plan_or_state
		body.L3Reachability.ProbeConfigIds = ListStringValueOrNil(ctx, plan.L3Reachability.ProbeConfigIds)
		// property: name=use_element_default, type=BOOLEAN macro=copy_from_plan_or_state
		if state.L3Reachability != nil {
			body.L3Reachability.UseElementDefault = ValueBoolPointerFromPlanOrState(plan.L3Reachability.UseElementDefault, state.L3Reachability.UseElementDefault)
		} else {
			body.L3Reachability.UseElementDefault = BoolValueOrNil(plan.L3Reachability.UseElementDefault)
		}
	}
	// property: name=label, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Label = ValueStringPointerFromPlanOrState(plan.Label, state.Label)
	} else {
		body.Label = StringValueOrNil(plan.Label)
	}
	// property: name=lqm_enabled, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.LqmEnabled = ValueBoolPointerFromPlanOrState(plan.LqmEnabled, state.LqmEnabled)
	} else {
		body.LqmEnabled = BoolValueOrNil(plan.LqmEnabled)
	}
	// property: name=name, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.Name = ValueStringPointerFromPlanOrState(plan.Name, state.Name)
	} else {
		body.Name = StringValueOrNil(plan.Name)
	}
	// property: name=probe_profile_id, type=STRING macro=copy_from_plan_or_state
	if state != nil {
		body.ProbeProfileId = ValueStringPointerFromPlanOrState(plan.ProbeProfileId, state.ProbeProfileId)
	} else {
		body.ProbeProfileId = StringValueOrNil(plan.ProbeProfileId)
	}
	// property: name=tags, type=SET_PRIMITIVE macro=copy_from_plan_or_state
	body.Tags = SetStringValueOrNil(ctx, plan.Tags)
	// property: name=use_for_application_reachability_probes, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.UseForApplicationReachabilityProbes = ValueBoolPointerFromPlanOrState(plan.UseForApplicationReachabilityProbes, state.UseForApplicationReachabilityProbes)
	} else {
		body.UseForApplicationReachabilityProbes = BoolValueOrNil(plan.UseForApplicationReachabilityProbes)
	}
	// property: name=use_for_controller_connections, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.UseForControllerConnections = ValueBoolPointerFromPlanOrState(plan.UseForControllerConnections, state.UseForControllerConnections)
	} else {
		body.UseForControllerConnections = BoolValueOrNil(plan.UseForControllerConnections)
	}
	// property: name=use_lqm_for_non_hub_paths, type=BOOLEAN macro=copy_from_plan_or_state
	if state != nil {
		body.UseLqmForNonHubPaths = ValueBoolPointerFromPlanOrState(plan.UseLqmForNonHubPaths, state.UseLqmForNonHubPaths)
	} else {
		body.UseLqmForNonHubPaths = BoolValueOrNil(plan.UseLqmForNonHubPaths)
	}
	// property: name=vpnlink_configuration, type=REFERENCE macro=copy_from_plan_or_state
	if plan.VpnlinkConfiguration == nil {
		body.VpnlinkConfiguration = nil
	} else {
		body.VpnlinkConfiguration = &sdwan_schema.VPNLinkConfiguration{}
		// copy_from_plan_or_state: body=body.VpnlinkConfiguration prefix=rsModel state=state.VpnlinkConfiguration plan=plan.VpnlinkConfiguration properties=2
		// property: name=keep_alive_failure_count, type=INTEGER macro=copy_from_plan_or_state
		if state.VpnlinkConfiguration != nil {
			body.VpnlinkConfiguration.KeepAliveFailureCount = ValueInt64PointerFromPlanOrState(plan.VpnlinkConfiguration.KeepAliveFailureCount, state.VpnlinkConfiguration.KeepAliveFailureCount)
		} else {
			body.VpnlinkConfiguration.KeepAliveFailureCount = Int64ValueOrNil(plan.VpnlinkConfiguration.KeepAliveFailureCount)
		}
		// property: name=keep_alive_interval, type=INTEGER macro=copy_from_plan_or_state
		if state.VpnlinkConfiguration != nil {
			body.VpnlinkConfiguration.KeepAliveInterval = ValueInt64PointerFromPlanOrState(plan.VpnlinkConfiguration.KeepAliveInterval, state.VpnlinkConfiguration.KeepAliveInterval)
		} else {
			body.VpnlinkConfiguration.KeepAliveInterval = Int64ValueOrNil(plan.VpnlinkConfiguration.KeepAliveInterval)
		}
	}

	// convert body to map
	json_body, err := json.Marshal(body)
	if err != nil {
		resp.Diagnostics.AddError("error marshaling struct WANInterfaceLabelScreenV2N5 to JSON:", err.Error())
		return false
	}

	// process http json path
	request_body_string := string(json_body)
	// copy pointer
	put_request.RequestBody = &request_body_string

	// Perform the operation.
	svc.ExecuteSdwanRequest(ctx, put_request)
	if put_request.ResponseErr != nil {
		if IsObjectNotFound(*put_request.ResponseErr) {
			State.RemoveResource(ctx)
		} else if r.GetHttpStatusCode(put_request) == 404 {
			State.RemoveResource(ctx)
		} else {
			tflog.Info(ctx, "update request failed for prismasdwan_wan_interface_label", map[string]any{
				"terraform_provider_function": "Update",
				"resource_name":               "prismasdwan_wan_interface_label",
				"path":                        put_request.FinalPath,
			})
			tflog.Debug(ctx, "update request failed for prismasdwan_wan_interface_label", map[string]any{
				"terraform_provider_function": "Update",
				"resource_name":               "prismasdwan_wan_interface_label",
				"path":                        put_request.FinalPath,
				"request":                     put_request.ToString(),
			})
			resp.Diagnostics.AddError("error updating prismasdwan_wan_interface_label", (*put_request.ResponseErr).Error())
		}
		return false
	}

	// process http json path
	response_body_string := string(*put_request.ResponseBytes)
	// inject overrides
	response_body_string, _ = sjson.Delete(response_body_string, "_created_on_utc")
	response_body_string, _ = sjson.Set(response_body_string, "_schema", 0)

	// start copying attributes
	var ans sdwan_schema.WANInterfaceLabelScreenV2N5
	// copy from json response
	json_err := json.Unmarshal([]byte(response_body_string), &ans)
	// if found, exit
	if json_err != nil {
		resp.Diagnostics.AddError("error in json unmarshal to WANInterfaceLabelScreenV2N5 in update", json_err.Error())
		return false
	}

	// Store the answer to state. schema=WANInterfaceLabelScreenV2N5
	// copy_to_state: state=state prefix=rsModel ans=ans properties=15
	// property: name=_etag, type=INTEGER macro=copy_to_state
	state.Etag = types.Int64PointerValue(ans.Etag)
	// property: name=_schema, type=INTEGER macro=copy_to_state
	state.Schema = types.Int64PointerValue(ans.Schema)
	// property: name=bwc_enabled, type=BOOLEAN macro=copy_to_state
	state.BwcEnabled = types.BoolPointerValue(ans.BwcEnabled)
	// property: name=description, type=STRING macro=copy_to_state
	state.Description = types.StringPointerValue(ans.Description)
	// property: name=id, type=STRING macro=copy_to_state
	state.Id = types.StringPointerValue(ans.Id)
	// property: name=l3_reachability, type=REFERENCE macro=copy_to_state
	if ans.L3Reachability == nil {
		state.L3Reachability = nil
	} else {
		state.L3Reachability = &rsModelWANL3Reachability{}
		// copy_to_state: state=state.L3Reachability prefix=rsModel ans=ans.L3Reachability properties=2
		// property: name=probe_config_ids, type=ARRAY_PRIMITIVE macro=copy_to_state
		varProbeConfigIds, errProbeConfigIds := types.ListValueFrom(ctx, types.StringType, ans.L3Reachability.ProbeConfigIds)
		state.L3Reachability.ProbeConfigIds = varProbeConfigIds
		resp.Diagnostics.Append(errProbeConfigIds.Errors()...)
		// property: name=use_element_default, type=BOOLEAN macro=copy_to_state
		state.L3Reachability.UseElementDefault = types.BoolPointerValue(ans.L3Reachability.UseElementDefault)
	}
	// property: name=label, type=STRING macro=copy_to_state
	state.Label = types.StringPointerValue(ans.Label)
	// property: name=lqm_enabled, type=BOOLEAN macro=copy_to_state
	state.LqmEnabled = types.BoolPointerValue(ans.LqmEnabled)
	// property: name=name, type=STRING macro=copy_to_state
	state.Name = types.StringPointerValue(ans.Name)
	// property: name=probe_profile_id, type=STRING macro=copy_to_state
	state.ProbeProfileId = types.StringPointerValue(ans.ProbeProfileId)
	// property: name=tags, type=SET_PRIMITIVE macro=copy_to_state
	varTags, errTags := types.SetValueFrom(ctx, types.StringType, ans.Tags)
	state.Tags = varTags
	resp.Diagnostics.Append(errTags.Errors()...)
	// property: name=use_for_application_reachability_probes, type=BOOLEAN macro=copy_to_state
	state.UseForApplicationReachabilityProbes = types.BoolPointerValue(ans.UseForApplicationReachabilityProbes)
	// property: name=use_for_controller_connections, type=BOOLEAN macro=copy_to_state
	state.UseForControllerConnections = types.BoolPointerValue(ans.UseForControllerConnections)
	// property: name=use_lqm_for_non_hub_paths, type=BOOLEAN macro=copy_to_state
	state.UseLqmForNonHubPaths = types.BoolPointerValue(ans.UseLqmForNonHubPaths)
	// property: name=vpnlink_configuration, type=REFERENCE macro=copy_to_state
	if ans.VpnlinkConfiguration == nil {
		state.VpnlinkConfiguration = nil
	} else {
		state.VpnlinkConfiguration = &rsModelVPNLinkConfiguration{}
		// copy_to_state: state=state.VpnlinkConfiguration prefix=rsModel ans=ans.VpnlinkConfiguration properties=2
		// property: name=keep_alive_failure_count, type=INTEGER macro=copy_to_state
		state.VpnlinkConfiguration.KeepAliveFailureCount = types.Int64PointerValue(ans.VpnlinkConfiguration.KeepAliveFailureCount)
		// property: name=keep_alive_interval, type=INTEGER macro=copy_to_state
		state.VpnlinkConfiguration.KeepAliveInterval = types.Int64PointerValue(ans.VpnlinkConfiguration.KeepAliveInterval)
	}
	return true
}

// Performs the Create(POST) Operation on the Resource
// TfID is pulled from plan to use in the creation request
// Path Parameters are encoded into TfID itself
func (r *wanInterfaceLabelResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Info(ctx, "executing resource create for prismasdwan_wan_interface_label")
	var plan rsModelWANInterfaceLabelScreenV2N5
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// this resource does not have a POST call defined, assuming that the PUT call is present and GET call is present
	// path=/sdwan/v2.5/api/waninterfacelabels/{wantinterface_label_id}

	// state in api servers
	var save rsModelWANInterfaceLabelScreenV2N5

	// create a new tfid
	var idBuilder strings.Builder
	params := MapStringValueOrNil(ctx, plan.TfParameters)
	// ensure all parameters are written
	wantinterface_label_id, ok := params["wantinterface_label_id"]
	if !ok {
		resp.Diagnostics.AddError("could not find wantinterface_label_id in x_parameters", "missing parameter")
		return
	}
	idBuilder.WriteString("wantinterface_label_id")
	idBuilder.WriteString("=")
	idBuilder.WriteString(*wantinterface_label_id)
	// both TFID MUST MATCH!
	plan.Tfid = types.StringValue(idBuilder.String())
	save.Tfid = types.StringValue(idBuilder.String())
	// make a get call instead
	gResp := resource.ReadResponse{
		Private:     resp.Private,
		Diagnostics: resp.Diagnostics,
	}
	if r.doGet(ctx, &save, &plan, &resp.State, &gResp) {
		// make a put to override
		uResp := resource.UpdateResponse{
			Private:     resp.Private,
			Diagnostics: resp.Diagnostics,
		}
		if r.doPut(ctx, &plan, &save, &resp.State, &uResp) {
			// push into state
			resp.Diagnostics.Append(resp.State.Set(ctx, &save)...)
		}
	}
}

// Performs the Read(GET) Operation on the Resource
// TfID is pulled from state to use in the read request
// Path Parameters are extracted TfID itself
func (r *wanInterfaceLabelResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {

	tflog.Info(ctx, "executing resource read for prismasdwan_wan_interface_label")
	var savestate, state rsModelWANInterfaceLabelScreenV2N5
	resp.Diagnostics.Append(req.State.Get(ctx, &savestate)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make a get call
	if r.doGet(ctx, &state, &savestate, &resp.State, resp) {
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	}
}

// Performs the Update(PUT) Operation on the Resource
// TfID is pulled from state to use in the read request
// Path Parameters are extracted TfID itself
// TfID must match in state and plan, else error is thrown
func (r *wanInterfaceLabelResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {

	tflog.Info(ctx, "executing resource update for prismasdwan_wan_interface_label")
	var plan, state rsModelWANInterfaceLabelScreenV2N5
	// copy state from TF
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// copy plan from TF
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// make a put call
	if r.doPut(ctx, &plan, &state, &resp.State, resp) {
		resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
	}
}

// Performs the Delete Operation on the Resource
// TfID is pulled from state to use in the deletion request
// Path Parameters are extracted from the TfID itself
func (r *wanInterfaceLabelResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {

	tflog.Info(ctx, "executing resource delete for prismasdwan_wan_interface_label")
	// some resources are auto deleted
	resp.State.RemoveResource(ctx)
}

func (r *wanInterfaceLabelResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("tfid"), req, resp)
}
